### PR TITLE
Get rid of some git deps and set up cargo-deny

### PR DESCRIPTION
**Pull request by poljar**
This will raise the bar on adding dependencies with licensing issues or vulnerabilities, as well as on adding new git-based dependencies.

A review commit-by-commit is advised.

### CODE REVIEW

**Review by andybalaam — APPROVED** [review]
Looks good, thanks!

**Comment by poljar** [comment]
@stefanceriu @jmartinesp, care to test this? Nothing should have changed, but it might be good to double check that https://github.com/matrix-org/matrix-rust-sdk/pull/4071/commits/058f05b8993b898c416db37c5fd6c3a07cd4c8a8 works fine.

**Comment by stefanceriu** [comment]
Just did, everything looks fine on my side 👍

**Comment by poljar** [comment]
Well seems like complement doesn't like that :pouting_cat:

**Pull request merged**
