### PR TITLE
base: Make `BaseRoomInfo` compatible with room version 11

### LINKED ISSUE #2439: `BaseRoomInfo` is not compatible with room version 11
In #2437, we upgraded Ruma to a version that includes most changes for room version 11 (new in Matrix v1.8). This PR adapts the code to be compatible with the changes in types for the code to compile, but it doesn't fully support room version 11.

In `m.room.create` events of room version 11, the `creator` field is gone and the `sender` field should be used instead. The Matrix v1.8 spec says that clients should just use the `sender` of the event for any room version, which we don't have in `MinimalStateEvent`.

I see 3 options for this:

1. Do not use the Ruma `RoomRedactionEventContent` type, but create a new one where the `creator` is still mandatory and copied from the `sender`. This should be backwards-compatible without any issue.
2. Change `MinimalStateEvent` to include `sender` and do not store these events in the room info in the state store, but load them from the room state events when loading the rooms. An advantage of this is that we can always add new state events in `BaseRoomInfo` without requiring database migrations.
3. Change `MinimalStateEvent` to include `sender` and make database migrations to fix the data in the store to include the sender.

I myself would prefer the second solution as I find it more extensible in the future, and avoids duplicating data in the state store.

### PR DESCRIPTION
**Pull request by zecakeh**
Closes #2439.

See commits messages for details.

The question is: do we need to write database migrations? It should only be necessary if a client already encountered a room version 11 `m.room.create` event.

### CODE REVIEW

**Comment by zecakeh** [comment]
Rebased on main

**Comment by zecakeh** [comment]
I wrote the migration for this as part of #2609

**Review by jplatte — APPROVED** [review]
Thanks!

**Comment by jplatte** [comment]
To make sure we don't merge this without a migration, closing in favor of #2609.

**Pull request closed without merging**
