### PR TITLE
Upgrade UniFFI, use proc-macros more

### PR DESCRIPTION
**Pull request by jplatte**
Taking the upgrade commit from #1587, and converting a fallible functions to prove it's possible and reduce UDL file size.

The `&str` to `String` change can be undone once the proc-macros support `&str`. AFAIK it doesn't make a difference for the generated bindings, right?

### CODE REVIEW

**Comment by poljar** [comment]
> Taking the upgrade commit from #1587, and converting a fallible functions to prove it's possible and reduce UDL file size.
> 
> The `&str` to `String` change can be undone once the proc-macros support `&str`. AFAIK it doesn't make a difference for the generated bindings, right?

Actually I wanted to transition towards using `String`, @Anderas has found some crashes which point towards a `&str` argument being garbage collected too soon on the `Swift` side.

**Review by poljar — APPROVED** [review]
This looks good, though perhaps it would be prudent to let @Anderas or @BillCarsonFr confirm.

**Review by Hywan — APPROVED** [review]
Looks good to me too.

**Comment by Hywan** [comment]
> The `&str` to `String` change can be undone once the proc-macros support `&str`. AFAIK it doesn't make a difference for the generated bindings, right?

For what I've seen, the bytes are copied over Rust anyway, so it doesn't make a huge difference in term of memory performance. And as @poljar said, I reckon it's better to give ownership over those strings to avoid complexity.

**Comment by Anderas** [comment]
> This looks good, though perhaps it would be prudent to let @Anderas or @BillCarsonFr confirm.

I'll build and integrate this today to confirm

**Review by Anderas — APPROVED** [review]
Apart from a small typo correction there are no breaking API changes here (as expected) and after some testing no runtime issues either (though this is because I have constrained the access to `OlmMachine` from a single thread).

This is a great change, bringing the UDL-less future even closer

**Pull request merged**
