### PR TITLE
Update ruma

### PR DESCRIPTION
**Pull request by jplatte**
I hope all the changes make sense. I could add some comments about the incoming / owned to-device requests, but am unsure where exactly. I feel for the future it may be better to not rely on `send_event_to_device::IncomingRequest` at all and instead replicate it in matrix-rust-sdk (probably with `txn_id` as a `Uuid` and potentially other differences).

### CODE REVIEW

**Comment by jplatte** [comment]
Thanks for always relaying CI feedback back to me, though I wonder why I don't just get emails. Is that a `.travis.yml` setting?

**Comment by poljar** [comment]
> Thanks for always relaying CI feedback back to me, though I wonder why I don't just get emails. Is that a `.travis.yml` setting?

I don't get them for PRs either, not sure if it's a setting considering that I didn't have to set anything on some other repos. :sweat_smile:

**Comment by jplatte** [comment]
Seems like you should get them, but me not? https://docs.travis-ci.com/user/notifications/#default-notification-settings

**Comment by poljar** [comment]
> Seems like you should get them, but me not? https://docs.travis-ci.com/user/notifications/#default-notification-settings

Yeah I get those, just not for pull requests. Seems like that's a separate setting, but still unsure where the inconsistency comes from.

**Comment by jplatte** [comment]
One solution to the CI issue would be switching to GitHub actions – personally I heavily dislike their workflows, but it seems I'm pretty much alone in that and it is easy to set up notifications either directly on GitHub or via email for that. There's also [builds.sr.ht](https://builds.sr.ht/) which we're using for Ruma, but that's not a free service like Travis and GA; also haven't actually set up email notifications there but IIRC it's easy to do so.

**Comment by poljar** [comment]
Email notifications seem to be missing this [on_pull_request](https://docs.travis-ci.com/user/notifications/#notifications-of-pr-builds) setting, or at least it seems to be missing from the docs. So it seems like this isn't supported at all.

**Comment by jplatte** [comment]
In any case – CI succeeded this time :)

**Comment by poljar** [comment]
>  I feel for the future it may be better to not rely on `send_event_to_device::IncomingRequest` at all and instead replicate it in matrix-rust-sdk (probably with `txn_id` as a `Uuid` and potentially other differences).

Yeah considering that there are now two different types for the request, we're probably gonna swap the owned one out since we're having a bit of a dissonance with the `UUID` vs `String` for the outgoing to-device requests/messages.

**Pull request merged**
