### PR TITLE
Use the latest git version of UniFFI

### PR DESCRIPTION
**Pull request by jplatte**
Not very impressive, I know 😅

Currently on hold, timeline API is more important.

### CODE REVIEW

**Comment by gnunicorn** [comment]
what's in that git revision that we want? why do we want to upgrade to it (now)?

**Comment by jplatte** [comment]
We want to start using the proc-macro frontend. CI just showed that there's a small shortcoming in it, it's great to have that kind of feedback ahead of the release. Also soon-ish after the mentioned UniFFI PR we should actually be able to use it for many more things, so it actually reduces boilerplate long before it can fully replace the UDL file.

**Review by gnunicorn — APPROVED** [review]
lgtm

**Comment by jplatte** [comment]
Marking as ready-for-review because I think upstream might have fixed the issue that was blocking this.

**Comment by jplatte** [comment]
Seems like it! 🎉

**Pull request merged**
