### PR TITLE
Bump ruma

### PR DESCRIPTION
**Pull request by julioromano**
This is to pave the way to the upcoming "polls" work.

### CODE REVIEW

**Comment by julioromano** [comment]
@jplatte if it's ok with you you can merge it yourself as soon as you review it.

**Comment by csmith** [comment]
I think the sdk currently points at the `lax-id-validation` branch in Ruma, so we probably need to merge the polls change into there and use that commit

**Comment by jplatte** [comment]
Yeah, please use this rev: 8b4ece2b0fa31be21eb1273a6e6bf32e09909480

**Comment by julioromano** [comment]
Done!

**Review by jplatte — APPROVED** [review]

**Pull request merged**
