### PR TITLE
feat(ui): Implement room subscriptions in `RoomList` + notification counts

### PR DESCRIPTION
**Pull request by Hywan**
Address #1911.

This PR does 4 things:

1. It implements the `matrix_sdk_ui::room_list::Room::subscribe` and `::unsubscribe` methods, with the appropriate tests. The FFI bindings are implemented too.
2. It implements `matrix_sdk_ui::room_list::Room::id()` as a shortcut to `room.inner_room().room_id()`. It's especially useful for FFI users where creating such a “full room” (`inner_room`) may be expensive.
3. It removes `matrix_sdk_ffi::RoomListItem::timeline()` in favor of `matrix_sdk_ffi::Room::add_timeline_listener()`. It also updates the latter to return a `RoomTimelineListenerResult { items: Vec<Arc<TimelineEvent>>, items_stream: TaskHandle }`, so that now, it's finally possible to stop a timeline listener stream. Previously, it was impossible.
4. It implements `Room::*unread_notifications`, because it was easy and quick :-)

### CODE REVIEW

**Review by stefanceriu — APPROVED** [review]
Tried this together with the new `full_room.addTimelineListener` api. It doesn't provide a taskHandle or throw anymore but everything seems to be fine.

**Review by stefanceriu — CHANGES_REQUESTED** [review]
After the most recent changes I do get back an `itemsStream` `TaskHandle` which I store but then backpagination fails with the following error:

```
(lldb) po error
▿ ClientError
  ▿ Generic : 1 element
    - msg : "No timeline listeners registered, can\'t paginate"
```

In happy news, notification unread counts seem to work fine 👍

**Review by stefanceriu — APPROVED** [review]
Works now, 🚀 it!

**Comment by Hywan** [comment]
Code coverage seems down, but all the tests are passing. Let's merge the PR manually.

**Pull request merged**
