### PR TITLE
fix(cargo): Prevent matrix-sdk-ffi to crash on iOS

### PR DESCRIPTION
**Pull request by Hywan**
Voodoo.

### CODE REVIEW

**Comment by stefanceriu** [comment]
I just tested this by building it once, adding a couple of logs in some of the crates and then running it again:
`cargo build -p matrix-sdk-ffi --target aarch64-apple-ios-sim --profile reldbg`
`Finished reldbg [optimized + debuginfo] target(s) in 2m 30s`

Which is definitely better than the normal 10 minutes it takes but considerably slower than normal debug

**Comment by jplatte** [comment]
For trying to fix the crashes, I think you should *individually* try

* `incremental = false`
* `debug-assertions = false`
* `overflow-checks = false`
* `codegen-units = 16`

as settings for `reldbg`. (there's a chance none of these individually fixes the crashes, then I'd try `incremental` plus one of the others)

**Comment by stefanceriu** [comment]
> For trying to fix the crashes, I think a good tactic would be to _individually_ try the following

I tried all of them separately and in combination with `incremental` but it still crashes. I tried on `dbg` though as that's the one we're really interested in to not crash

**Comment by stefanceriu** [comment]
Okay, after way too many builds I tracked it down to `opt-level = 3`. Adding that to `dbg`, and that alone, stops it from crashing.

**Review by jplatte — CHANGES_REQUESTED** [review]
Noo! We can have a new profile, but the custom debug profile with full debug info should not use `opt-level = 3`!

**Pull request closed without merging**
