### PR TITLE
indexeddb: fix incorrect key used for next batch token

### PR DESCRIPTION
**Pull request by maan2003**
discovered during trying to use matrix-sdk-ui on wasm.

### CODE REVIEW

**Review by bnjbvr — APPROVED** [review]
ouch, good catch, thanks!

`ACCOUNT` is used in the `save_pending_changes` method, and `NEXT_BATCH_TOKEN` in `save_changes` (we're in the middle of refactoring that, and that refactoring has been interrupted). Basically it would be an issue if `save_changes` was called *after* `save_pending_changes`, and ymmv but it seems this only happens in one of the FFI methods (`migrate_data`), from a quick skim, and that's probably why we hadn't noticed it.

And also when trying to read the token from the db, as in... sliding sync.

Thanks for reporting! Did you manage to get the UI crate to compile on wasm, and start writing bindings for it? We'd certainly be interested in upstreaming those changes to the repository :eyes: 

(Also, would you be willing to write a regression that that would have failed without this patch? Not mandatory, but just asking in case you have free time and lots of good will :-))

**Comment by maan2003** [comment]
I have bunch of wasm changes at https://github.com/maan2003/matrix-rust-sdk/commits/hacks/

I will clean it up and upstream it once it is mostly working. Bindings are not open source mostly because we (at work) are not using wasm_bindgen [^1]



--- 

Sorry, I don't have time to write regression test for this. In future, I would like to write an end-to-end wasm integration test that catches such regressions.

[^1]: we have to support react native on mobile and wasm on web. react native doesn't support uniffi well. So we roll our own bindings layer.

**Comment by maan2003** [comment]
You haven't noticed this because this only happens in wasm (matrix-sdk-indexeddb) and sliding sync doesn't even compile to wasm.

**Comment by bnjbvr** [comment]
Thanks for the additional context.

**Pull request merged**
