### PR TITLE
Increase backoff for failed servers and users with exhausted OTKs

### PR DESCRIPTION
**Pull request by richvdh**
Fixes https://github.com/matrix-org/matrix-rust-sdk/issues/2804

- [x] Public API changes documented in changelogs (optional)

### CODE REVIEW

**Review by poljar — CHANGES_REQUESTED** [review]
There's some discussion at https://github.com/matrix-org/matrix-rust-sdk/issues/2804 which I largely agree with.

In short, this PR will result in the increased number of UTDs.

What needs to be done before we can ponder how to change the values is to allow the `FailuresCache` to accept different sets for values. A new constructor should be added `FailuresCache::with_timeouts(start: u64, max: u64)` which will override the default values.

Then we can ponder which usage of the `FailuresCache` should use different values.

**Comment by poljar** [comment]
>  Increase backoff for failed servers #2858 

Another thing, this is slightly misleading, it will also increase the backoff for the one-time key exhaustion case.

**Comment by richvdh** [comment]
> > Increase backoff for failed servers #2858
> 
> Another thing, this is slightly misleading, it will also increase the backoff for the one-time key exhaustion case.

Yes, true. I've updated the summary to be more explicit, hopefully.

**Comment by richvdh** [comment]
per my comments on #2804: closing this for now as it seems to be good enough.

**Pull request closed without merging**
