### PR TITLE
Build Node bindings against Ubuntu 20.04

### LINKED ISSUE #1808: Node.JS bindings are being built against ubuntu-latest, which causes glibc incompatibilties
Basically a repeat of #968. We resolved in the issue to use the previous Ubuntu LTS, which is currently 20.04 LTS. 

https://github.com/matrix-org/matrix-rust-sdk/blob/main/.github/workflows/release-crypto-nodejs.yml#L41-L66

### PR DESCRIPTION
**Pull request by AndrewFerr**
Should fix #1808

- [ ] Public API changes documented in changelogs (optional)

Signed-off-by: Andrew Ferrazzutti [andrewf@element.io](mailto:andrewf@element.io)

### CODE REVIEW

**Comment by AndrewFerr** [comment]
Ah, this conflicts with `main` since the Node bindings release workflow PR was reverted.  Maybe we could resolve both the [linux-musl build issue](https://github.com/matrix-org/matrix-rust-sdk/actions/runs/4697562772/jobs/8329227545#step:8:217) & the [glibc compatibility issue](https://github.com/matrix-org/matrix-rust-sdk/issues/968) all in one shot here?

**Comment by AndrewFerr** [comment]
By the way, I've confirmed that using this release lets me run [matrix-appservice-bridge](https://github.com/matrix-org/matrix-appservice-bridge)'s tests (after having added a dependency on the crypto bindings) in a local Docker container of `ubuntu:20.04`, whereas using the prior beta release hits the same glibc error as seen in CI workflows ([example](https://github.com/matrix-org/matrix-appservice-bridge/actions/runs/4787057253/jobs/8511786007?pr=466#step:5:10)).

**Review by Hywan — COMMENTED** [review]
Can you explain as a YAML comment why we aren't using `ubuntu-latest` please? It will help to keep the knowledge in the appropriate place.

**Comment by Hywan** [comment]
> Ah, this conflicts with `main` since the Node bindings release workflow PR was reverted. Maybe we could resolve both the [linux-musl build issue](https://github.com/matrix-org/matrix-rust-sdk/actions/runs/4697562772/jobs/8329227545#step:8:217) & the [glibc compatibility issue](https://github.com/matrix-org/matrix-rust-sdk/issues/968) all in one shot here?

I'm OK to resolve both at the same time here.

**Comment by AndrewFerr** [comment]
> Can you explain as a YAML comment why we aren't using ubuntu-latest please? It will help to keep the knowledge in the appropriate place.

Done via 4bf6ce0.

> I'm OK to resolve both at the same time here.

From what I can tell from [the logs for running the prerelease workflow on this commit](https://github.com/matrix-org/matrix-rust-sdk/actions/runs/4788889481), there were no issues with any of the prebuilt libraries, even those for linux-musl.  Is there anything else that needs to be done to fix the release process?

**Comment by AndrewFerr** [comment]
I'll rebase this on the latest tip of `main` to see if the release workflow works with it (but will cancel before a release is published)

**Comment by AndrewFerr** [comment]
Ah, rebasing allowed CI to run & reveal build issues.  I'll look into it

**Comment by AndrewFerr** [comment]
As expected, the release workflow failed on the linux-musl build: https://github.com/matrix-org/matrix-rust-sdk/actions/runs/4808018200/jobs/8557495133

I'll try again with my PR re-applied to confirm whether or not it works.

**Comment by AndrewFerr** [comment]
Alright, restoring the linux-musl workflow change does let the release get built: https://github.com/matrix-org/matrix-rust-sdk/actions/runs/4808312230  (I cancelled the npm publish step to not publish it before we're okay with it.)

It looks like everything is fine with this; is there something missing?

**Review by Hywan — APPROVED** [review]

**Pull request merged**
