### PR TITLE
feat(timeline): introduce the `TimelineUniqueId`

### PR DESCRIPTION
**Pull request by bnjbvr**
See commit by commit description.

Extracted from #4100.

### CODE REVIEW

**Review by stefanceriu — CHANGES_REQUESTED** [review]
This looks good to me. There's a bunch of changes we will need to make on the iOS side but I think it's about time, they're welcome.

**Comment by bnjbvr** [comment]
See https://github.com/matrix-org/matrix-rust-sdk/pull/4100#issuecomment-2413529652. From this PR we can keep the first commit (don't try to reuse unique IDs) + the opaque type, and we'll get rid of the third one likely. It might be better to *not* use the transaction unique id in the react function first.

**Comment by bnjbvr** [comment]
Ready for another round of review, after/on-top-of https://github.com/matrix-org/matrix-rust-sdk/pull/4127 (but since you're the reviewer, you choose to decide how you review all this :)). Thanks!

**Review by stefanceriu — APPROVED** [review]
Just tried it out in [on this branch and on top of 4127](https://github.com/element-hq/element-x-ios/tree/stefan/rust4127) and everything looks good to me. Nicely done 👍

**Pull request merged**
