### PR TITLE
fix(sdk): limit the number of retries when updating push rules.

### PR DESCRIPTION
**Pull request by nimau**
This PR limits the number of retries when updating the push rules.

### CODE REVIEW

**Comment by bnjbvr** [comment]
Hi, thanks for the PR, code looks fine, but can you give more context to the change, please? Was it an issue, and if so, how/why?

**Comment by nimau** [comment]
> Hi, thanks for the PR, code looks fine, but can you give more context to the change, please? Was it an issue, and if so, how/why?

As the number of retry is not limited, the SDK never stops trying to update the push rules and no error is reported to the client application, which will wait indefinitely for either a success or an error.

**Review by bnjbvr — APPROVED** [review]
Thanks, that makes sense.

**Comment by bnjbvr** [comment]
@nimau To fix the CI error, can you rebase on top of main please?

**Comment by nimau** [comment]
> @nimau To fix the CI error, can you rebase on top of main please?

Yes, of course.

**Pull request merged**
