### PR TITLE
fix(crypto): Be more restrictive around Megolm session rotation periods

### PR DESCRIPTION
**Pull request by poljar**

### CODE REVIEW

**Review by jplatte — COMMENTED** [review]
This seems to contain two unrelated changes that should probably be individual commits (removing the `compile_error!` and moving that one test), but the main change seems reasonable.

**Comment by poljar** [comment]
> This seems to contain two unrelated changes that should probably be individual commits (removing the `compile_error!` and moving that one test), but the main change seems reasonable.

I have split them out into separate commits now.

**Review by jplatte — APPROVED** [review]
I don't really get what the move of the test is about and it's still in the same commit as the session rotation clamping, but I'm sure there's a good reason and maybe it's related enough that it should be in one commit.

**Comment by poljar** [comment]
> I don't really get what the move of the test is about and it's still in the same commit as the session rotation clamping, but I'm sure there's a good reason and maybe it's related enough that it should be in one commit.

It's about having access to the `message_count` private field of the `OutboundGroupSession` struct. Otherwise we would have to either encrypt 10_000 messages, or make the field public.

**Pull request merged**
