### PR TITLE
crypto: Rename msk to master_key for consistency with the wider codebase

### PR DESCRIPTION
**Pull request by andybalaam**
As suggested in https://github.com/matrix-org/matrix-rust-sdk/pull/3590#discussion_r1671945866

Part of https://github.com/matrix-org/matrix-rust-sdk/issues/3543

### CODE REVIEW

**Review by bnjbvr — APPROVED** [review]
Looks like this wasn't tested at all :eyes: Bonus points if you add a test that reads and checks those values.

**Review by poljar — APPROVED** [review]
Thank you.

**Comment by poljar** [comment]
> Looks like this wasn't tested at all 👀 Bonus points if you add a test that reads and checks those values.

It's unused as of now, it will become used as part of #3590, where it is also tested. It was spit out for easier review.

**Comment by andybalaam** [comment]
> Looks like this wasn't tested at all 👀 Bonus points if you add a test that reads and checks those values.

Thank you for your diligence and ordinarily I would enthusiastically agree but see @poljar 's answer :-)

It is unfortunate that this change is so big that I needed to break it up in annoying ways. Maybe we could have found a better way to break it up that formed individual functional changes, but I couldn't find one when I tried.

**Pull request merged**
