### PR TITLE
chore: Bump MSRV in READMEs

### PR DESCRIPTION
**Pull request by zecakeh**
To match the version in `Cargo.toml`.

### CODE REVIEW

**Comment by zecakeh** [comment]
Alternatively they could just be removed from the README. It used to be nice to have it because there was no other place to set it, but now that it appears explicitly in `Cargo.toml` it is not necessary anymore.

**Comment by poljar** [comment]
> Alternatively they could just be removed from the README. It used to be nice to have it because there was no other place to document it, but now that it appears explicitly in Cargo.toml it is not necessary anymore.

Yeah, I don't think there's much point in having them in two places.

**Comment by stefanceriu** [comment]
I was just about to ask. I disabled automerge and will wait for that change.

**Comment by zecakeh** [comment]
Alright, I pushed a commit that removed the MSRV from the READMEs instead.

**Pull request merged**
