### PR TITLE
matrix-sdk: Add `full` feature

### PR DESCRIPTION
**Pull request by johannescpk**
Should speed up CI a bit and should also help with working on https://github.com/matrix-org/matrix-rust-sdk/pull/204#discussion_r629086520

### CODE REVIEW

**Comment by jplatte** [comment]
Does `--all-features` not work if this is just for CI?

**Comment by johannescpk** [comment]
> Does `--all-features` not work if this is just for CI?

`rust-tls` and `native-tls` are mutually exclusive, so I think `--all-features` doesn't work

**Comment by johannescpk** [comment]
That's probably a question for @poljar and might be out of scope of this PR

**Comment by poljar** [comment]
I think reqwest used to work this way as well? Anyways no objections in changing this so we get `--all-features` back.

**Comment by jplatte** [comment]
No, not really. Maybe @poljar wants to implement that, or merge this as an intermediate step.

**Comment by johannescpk** [comment]
I'll convert this to draft and wait for the outcome of #204 since that would generate a conflict otherwise

**Comment by johannescpk** [comment]
Closing this for now since CI runtimes seem to be currently a non-issue

**Pull request closed without merging**
