### PR TITLE
fix(ffi): match the right status code in `Client::is_room_alias_available`

### PR DESCRIPTION
**Pull request by jmartinesp**
Previously I was matching a different error state, so it turns out the code was failing 🫠 .

- [ ] Public API changes documented in changelogs (optional)

Signed-off-by:

### CODE REVIEW

**Review by poljar — APPROVED** [review]
How come we don't need to change a test? Could it be that we don't have one? :fearful: 

Anyways, would be nice to add it now.

**Comment by jmartinesp** [comment]
Will FFI layer tests run in the CI? If so, I'll add one, I thought they didn't 🫤 .

**Comment by poljar** [comment]
> Will FFI layer tests run in the CI? If so, I'll add one, I thought they didn't 🫤 .

Doesn't seem like it.

I think that we should either enable them or move the bulk of the logic to the main crate and add a test there. Fixing a bug without a test sounds worse to me.

**Comment by jmartinesp** [comment]
Moved the fn to the SDK crate and added some tests, now the FFI layer only maps some values and calls the inner function.

**Review by poljar — APPROVED** [review]
Nice, thanks for adding the test.

Small reminder, please use the `MatrixMockServer` for new tests in the future.

**Comment by jmartinesp** [comment]
I implemented a new endpoint in `MatrixMockServer` for this, I'll merge the PR as soon as the CI is finished.

**Pull request merged**
