### PR TITLE
matrix-sdk: Add function to get users and room avatar

### PR DESCRIPTION
**Pull request by jsparber**

### CODE REVIEW

**Comment by zecakeh** [comment]
How about exposing the `method` field as a function param to allow an app to chose completely the format? It's not in the spec, but according to [this issue](https://github.com/matrix-org/matrix-doc/issues/2658) the default for synapse seems to be `scale`, although usually apps only need a square image. They might also want on the contrary the full image with a maximum size.

**Comment by poljar** [comment]
> How about exposing the `method` field as a function param to allow an app to chose completely the format? It's not in the spec, but according to [this issue](https://github.com/matrix-org/matrix-doc/issues/2658) the default for synapse seems to be `scale`, although usually apps only need a square image. They might also want on the contrary the full image with a maximum size.

I agree with this, there should be a way to get the full-sized image. 

I'm also inclined to suggest that we should completely ignore server-side thumbnailing since it doesn't work for encrypted uploads, and right away just implement it client-side. This way you get the full-sized image and you thumbnail locally, clients can display both versions then without any additional requests.

There are of course downsides to this, namely bandwidth usage and CPU usage increase.

**Comment by jsparber** [comment]
> How about exposing the method field as a function param to allow an app to chose completely the format? It's not in the spec, but according to this issue the default for synapse seems to be scale, although usually apps only need a square image. They might also want on the contrary the full image with a maximum size.
@zecakeh i didn't expose the `method` field since to me it seams like you pretty much want to crop and scale in most cases. E.g. scale do a specific size and then crop it to a square, which isn't possible via the server. Anyways I can add it.
> I agree with this, there should be a way to get the full-sized image.
The user gets the full-sized when the requested size is bigger then the full-size of the image. I think in the case of the avatar I don't see any point in downloading the full-size if the application will never display the avatar full-sized. We could make `width` and `height` optional and download the full-sized avatar when they aren't provided.

**Comment by poljar** [comment]
> The user gets the full-sized when the requested size is bigger then the full-size of the image. I think in the case of the avatar I don't see any point in downloading the full-size if the application will never display the avatar full-sized. We could make `width` and `height` optional and download the full-sized avatar when they aren't provided.

The user might not know the full size, e.g. the sizes in `ImageInfo` of the avatar are completely optional. 

Won't the application display the full size if the user clicks on the avatar? It seems that at leas Element does that, it also allows you to save the full-sized avatar.

**Comment by zecakeh** [comment]
> @zecakeh i didn't expose the `method` field since to me it seams like you pretty much want to crop and scale in most cases. E.g. scale do a specific size and then crop it to a square, which isn't possible via the server. Anyways I can add it.

The way I understand the spec is that using `crop` does scale and then crop. That's what makes the most sense to me anyway

**Comment by jsparber** [comment]
> Won't the application display the full size if the user clicks on the avatar? It seems that at leas Element does that, it also allows you to save the full-sized avatar.

True. But element downloads the full-sized avatar only once the avatar is viewed in the media viewer. 


> There are of course downsides to this, namely bandwidth usage and CPU usage increase.

I think this is a really good reason not to download the room avatar (or room members avatar) in it's full sizl till it's actually needed. The image size won't have a huge impact when the user only has a couple of rooms but with a growing number of rooms this will have a bigger impact. Also, note that a room could have huge images as avatar.
I guess we could always download the user's own avatar at full-size, but i would like to keep the API consistent.

**Comment by jsparber** [comment]
> The way I understand the spec is that using crop does scale and then crop. That's what makes the most sense to me anyway.
You are right. I think this API is pretty odd :)

**Comment by poljar** [comment]
> I think this is a really good reason not to download the room avatar (or room members avatar) in it's full size till it's actually needed. The image size won't have a huge impact when the user only has a couple of rooms but with a growing number of rooms this will have a bigger impact. Also, note that a room could have huge images as avatar.

In that case let's make the sizes optional, like you suggested.

**Comment by poljar** [comment]
> Also if you request `1200x900, scale` it will still send the `800x600, scale` instead of the full size. [Synapse violates the spec in this case](https://github.com/matrix-org/synapse/issues/5302), and there's a bunch of other issues about thumbnails sizes too.

Right, issues like that and no E2EE support is why I dislike server-side thumbnailing.

**Comment by jsparber** [comment]
@poljar @zecakeh Do you still think we should expose the `method` or use one value as default?

**Comment by poljar** [comment]
> @poljar @zecakeh Do you still think we should expose the `method`?

I don't have a strong opinion about exposing `method`.

**Comment by zecakeh** [comment]
In a perfect world where you could actually get the size you are requesting I would expose it. But right now, as Synapse handles it, it would bring more confusion than anything…

**Comment by zecakeh** [comment]
It really boils down to this choice: do we want this API to honor the spec, meaning the SDK has to transform the images locally, or do we want to keep the current synapse behavior, in which case the docs have to explain how it differs from the spec.

It would go with the former that way we can just remove the quirks when the servers become compliant, without breaking the API. That relieves the burden from the developers that use the SDK. However, contrary to @poljar, I do believe that we should only request the closest thumbnail if possible, to save resources, especially on big rooms.

**Comment by zecakeh** [comment]
Maybe the docs could reference Synapse issues to clarify this:

> No guarantee on the size of the image is given.

The related issues: https://github.com/matrix-org/synapse/issues/1222, https://github.com/matrix-org/synapse/issues/1259, https://github.com/matrix-org/synapse/issues/1465, https://github.com/matrix-org/synapse/issues/5302

**Comment by jsparber** [comment]
> Maybe the docs could reference Synapse issues to clarify this:
> 
> > No guarantee on the size of the image is given.
> 
> The related issues: [matrix-org/synapse#1222](https://github.com/matrix-org/synapse/issues/1222), [matrix-org/synapse#1259](https://github.com/matrix-org/synapse/issues/1259), [matrix-org/synapse#1465](https://github.com/matrix-org/synapse/issues/1465), [matrix-org/synapse#5302](https://github.com/matrix-org/synapse/issues/5302)

I wouldn't expose to much about the underlying issues to the user, since it may create more confusion then clarify the issue. Anyhow, any suggestion on the specific wording?

**Comment by zecakeh** [comment]
No, this is fine.

**Comment by jsparber** [comment]
@poljar do you like me to change something else?

**Comment by poljar** [comment]
Ah, no. Let's merge this. It just fell off of my radar.

**Comment by jsparber** [comment]
> Ah, no. Let's merge this. It just fell off of my radar.

Same for me :)

**Pull request merged**
