### PR TITLE
Hotfix/crypto 0.3.14/qr code

### PR DESCRIPTION
**Pull request by BillCarsonFr**
Expose some missing API to fix https://github.com/vector-im/element-android/issues/8653

**SHOULD NOT BE MERGED**
It's a maintanance branch for the currently released android sdk

- [ ] Public API changes documented in changelogs (optional)

Signed-off-by:

### CODE REVIEW

**Comment by poljar** [comment]
The first commit seems to be part of main: https://github.com/matrix-org/matrix-rust-sdk/commit/1d08ffa05e4aafd138eb99d07454e04088b01b3a?

**Comment by BillCarsonFr** [comment]
> The first commit seems to be part of main: [1d08ffa](https://github.com/matrix-org/matrix-rust-sdk/commit/1d08ffa05e4aafd138eb99d07454e04088b01b3a)?

I updated the base

**Comment by jplatte** [comment]
Just realized that my review was requested here. Though given "SHOULD NOT BE MERGED" in the issue description, why does this PR exist in the first place? I'm a bit confused.

**Comment by BillCarsonFr** [comment]
> Just realized that my review was requested here. Though given "SHOULD NOT BE MERGED" in the issue description, why does this PR exist in the first place? I'm a bit confused.

It's a maintenance branch on an old version of the sdk for the android bindings. Android bindings are a bit late and we needed a hotfix.

**Comment by jplatte** [comment]
Okay, have restored the branch since it kinda sounds like it's still needed? Unlike the PR..

**Pull request closed without merging**
