### PR TITLE
Fix #3277 - Process profiles for all room members not only state even…

### LINKED ISSUE #3277: Invited room members missing display names and avatars
Related to https://github.com/element-hq/element-x-ios/issues/2392

Members fetched through [matrix-sdk.room.members](https://github.com/matrix-org/matrix-rust-sdk/blob/main/crates/matrix-sdk/src/room/mod.rs#L624) (used from [the ffi layer](https://github.com/matrix-org/matrix-rust-sdk/blob/main/bindings/matrix-sdk-ffi/src/room.rs#L184)) and which are in the `Invited` state are missing profiles (display names, avatars).

<del>The problem seems to stem from [this in the sdk-base client](https://github.com/matrix-org/matrix-rust-sdk/blob/main/crates/matrix-sdk-base/src/client.rs#L1174) which intentionally ignores profiles for members which aren't the state event sender.</del>

### PR DESCRIPTION
**Pull request by stefanceriu**
…t senders

### CODE REVIEW

**Review by poljar — APPROVED** [review]
Makes sense.

**Comment by bnjbvr** [comment]
Since this fixes a regression, could you add a regression test ad a follow-up, so we don't break this ever again?

**Comment by stefanceriu** [comment]
> could you add a regression test ad a follow-up

I would've loved to but I couldn't find any existing tests to inspire myself from. Any ideas? Are there more base-sdk client tests anywhere else?

**Comment by bnjbvr** [comment]
It seems the previous code existed for the reason that a sender can easily fake another person's profile, after the person's been banned/kicked: had you seen it?

https://github.com/matrix-org/matrix-rust-sdk/blob/ac0bc95c253c5d46fec31378016497f433e0067d/crates/matrix-sdk-base/src/client.rs#L521-L527

**Pull request merged**
