### PR TITLE
Documentation on `/keys/query` parsing functions

### PR DESCRIPTION
**Pull request by richvdh**
These functions are a bit confusing, so I wrote some comments. I also factored out `get_user_signing_key_from_response`, to reduce duplication and (IMHO) improve clarity.

### CODE REVIEW

**Comment by richvdh** [comment]
Waiting for https://github.com/matrix-org/matrix-rust-sdk/pull/2674 to land before finishing this

**Comment by jplatte** [comment]
@richvdh I think you meant to link to a different PR there 😉

**Comment by richvdh** [comment]
sigh, yes I did. #2676.

**Review by poljar — APPROVED** [review]
Found a typo, otherwise looks good.

**Pull request merged**
