### PR TITLE
sdk-ffi apple workflow optimization

### PR DESCRIPTION
**Pull request by stefanceriu**
This PR will make the debug script only use the active architecture as passed by Xcode which should significantly delay build times (as opposed to both arm64 and intel simulators).
It will also remove the Mac Catalyst target build step and name module maps correctly for xcframeworks.

### CODE REVIEW

**Review by Hywan — APPROVED** [review]
It looks good to me, thank you!

**Comment by Hywan** [comment]
You may want to rebase on the actual `main` branch, which could solve the failing tests probably.

**Comment by Hywan** [comment]
The CI is broken. Should we revert this patch, or @stefanceriu, can you open a new PR to fix it please?

Logs: https://github.com/matrix-org/matrix-rust-sdk/runs/7317990124?check_suite_focus=true#step:8:26

**Comment by stefanceriu** [comment]
I'm currently unavailable but I think the problem is that the Mac runner is now targeting 15.4 instead of the 15.4 the tests script is looking for as a destination, so not related to this PR. We might get away with just removing the platform altogether. I'll try fixing it on monday if you don't do so in the meantime.

**Pull request merged**
