### PR TITLE
WIP: matrix-sdk-base: store timeline to StateStore

### PR DESCRIPTION
**Pull request by jsparber**
Since #141 is stale for some time already. I took a shot at storing the timeline to the StateStore.
Obviously takes inspiration from #141

This still needs the implementation for the SledStore.

### CODE REVIEW

**Comment by DevinR528** [comment]
Hmm yeah, #141 should be closed in favor of this for sure, unless we want it around to refer to but #230 would probably be better for that. It might be worthwhile to look at #230 as closer to what it may end up being.

This question https://github.com/matrix-org/matrix-rust-sdk/pull/230#issuecomment-843396414 I'm still not sure how to answer.

**Comment by jsparber** [comment]
> Hmm yeah, #141 should be closed in favor of this for sure, unless we want it around to refer to but #230 would probably be better for that. It might be worthwhile to look at #230 as closer to what it may end up being.
> 
> This question [#230 (comment)](https://github.com/matrix-org/matrix-rust-sdk/pull/230#issuecomment-843396414) I'm still not sure how to answer.

Oh i didn't see #230. 

I'm using a different approach to store timeline pages (TimelineSlices). They are just dumped to the store without any order, because we will eventually always end up with gaps in the known timeline. Also the `TimelineSlices` build a linked list via the start and end token. In addition, this method requires us only to store `EventId -> TimelineSlice`. The `TimelineSlice` uses the the start token as a key, it would also be possible to use something different to reduce the size of the key.

**Comment by jsparber** [comment]
This MR is pretty much finished but needs some better tests and it contains to FIXME which I would like to address before removing WIP.

**Comment by jsparber** [comment]
since this started with the wrong idea i will open a new MR.

**Pull request closed without merging**
