### PR TITLE
feat(ffi): Improve performances of `Room::members`

### PR DESCRIPTION
**Pull request by Hywan**
This PR contains several patches. It can be reviewed commit-by-commit.

The first set of patches makes `fetch_members`, `members` and `member` async. Why? Because some callers of the bindings would like to “cancel” `Room::fetch_members` or `Room::members` for example, which is easier to do when the methods are purely async.

THe second set of patches makes `members` to return a `RoomMembersIterator`, which “implements” `ChunkIterator`, a new type.

---

* Address https://github.com/matrix-org/matrix-rust-sdk/issues/1979

### CODE REVIEW

**Review by jplatte — APPROVED** [review]
It's rather scary that only clippy complained when you used `RefCell` instead of `RwLock`. UniFFI should not accept non-thread-safe `Arc`s...

**Comment by Hywan** [comment]
My local Clippy didn't complained about it neither (rustc 1.74.0-nightly (a991861ec 2023-09-05)) :-/.

**Comment by Hywan** [comment]
https://github.com/mozilla/uniffi-rs/pull/1727 might prevent this, no?

**Comment by jplatte** [comment]
Maybe, but I've just opened https://github.com/mozilla/uniffi-rs/pull/1740 which will definitely fix it for object types.

**Comment by ganfra** [comment]
Should this be merged?

**Pull request merged**
