### PR TITLE
Extract functions to shorten the `process_sliding_sync_room` method

### PR DESCRIPTION
**Pull request by andybalaam**
Extract a couple of functions to shorten the `process_sliding_sync_room` method

Applies on top of https://github.com/matrix-org/matrix-rust-sdk/pull/2043

### CODE REVIEW

**Comment by Hywan** [comment]
Is it ready for a review?

**Comment by andybalaam** [comment]
> Is it ready for a review?

Yes please

**Review by Hywan — APPROVED** [review]
Excellent, thanks!

**Comment by bnjbvr** [comment]
(restarting CI the hard way)

**Pull request merged**
