### PR TITLE
FFI: Remove the authentication service.

### LINKED ISSUE #3029: Move the authentication service into the main SDK.
The authentication service grew too big for the FFI a long time ago. It needs moving into the main SDK and properly covering with tests.

### PR DESCRIPTION
**Pull request by pixlwave**
Everything is now available on Client directly, the authentication service is no longer needed. Can be reviewed commit by commit.

This closes #3029.

Of note for people adopting this:
- Instead of calling `configure_homeserver`, build your own `Client` with the `serverNameOrHomeserverUrl` builder method to keep the same behaviour.
    - The parts of `AuthenticationError` related to discovery will be represented in the `ClientBuildError` returned when calling `build()`.
- The remaining methods can be found on the built `Client`.
    - There is a new `abortOidcLogin` method that should be called if the webview is dismissed without a callback (or fails to present).
    - The remaining `AuthenticationError` cases are now in an `OidcError` type.
- `OidcAuthenticationData` is now called `OidcAuthorizationData`.

### CODE REVIEW

**Review by andybalaam — CHANGES_REQUESTED** [review]
Looks great - just needs a changelog entry! (Basically re-use your PR description?)

**Comment by pixlwave** [comment]
Added it - there wasn't one on the FFI so I copied the format from the main SDK.

**Review by andybalaam — APPROVED** [review]
Looks good, thanks!

**Comment by andybalaam** [comment]
@pixlwave I see some value in the separate commits here, so would prefer not to squash-merge. Do you feel like doing the work to rebase to remove the fix-up commits? If not I'll just squash.

**Comment by pixlwave** [comment]
Good point, done 👍

**Comment by jmartinesp** [comment]
I just want to confirm these changes seem to work fine on Android after adding the needed changes.

**Comment by pixlwave** [comment]
@andybalaam Do you think we can ignore that complement failure? It happily picked up the branch name [before](https://github.com/matrix-org/matrix-rust-sdk/actions/runs/9612316180/job/26513084129#step:3:55) (and passed) but after the rebase is seemingly having a [hard time](https://github.com/matrix-org/matrix-rust-sdk/actions/runs/9614245295/job/26519495755#step:3:45) with it. I vow not to use emoji in branch names again 🥺

**Comment by bnjbvr** [comment]
> @andybalaam Do you think we can ignore that complement failure? It happily picked up the branch name [before](https://github.com/matrix-org/matrix-rust-sdk/actions/runs/9612316180/job/26513084129#step:3:55) (and passed) but after the rebase is seemingly having a [hard time](https://github.com/matrix-org/matrix-rust-sdk/actions/runs/9614245295/job/26519495755#step:3:45) with it. I vow not to use emoji in branch names again 🥺

I'll be the party pooper here, sorry. Can you reopen this PR with a different branch name? There's no way to know if it actually passes the Complement tests or not, in the current form. (And yeah, it might be that some code in the branch matching resolving doesn't account for non-ascii UTF8 :grin:)

**Comment by pixlwave** [comment]
Ok. Lemme try rebasing on main first and see if that nudges it 🤞 If not I'll do a new PR.

**Comment by pixlwave** [comment]
Nice, then emoji branch in names can remain a valid choice 😎

**Pull request merged**
