### PR TITLE
fix(sdk): Can't assert identity without session

### LINKED ISSUE #821: `Client::send` fails with `assert_identity` enabled [regression]
**Describe the bug**
Due to the refactoring in https://github.com/matrix-org/matrix-rust-sdk/commit/12d1607cdce6b63eb45195283d08160e40bc77a2 it is no longer possible to enable `assert_identity` and then `Client::send()` requests that don't pass a `session` to the underlying `HttpClient::send()`. In turn this means that `Client::send` generally no longer works anymore, as it is calling `Client::server_versions()` internally, which passes `None` as session.

**To Reproduce**
Instantiate `Client` with `assert_identity` enabled and try to `Client::send()` a request.

**Additional context**

Supersedes https://github.com/matrix-org/matrix-rust-sdk/issues/819

### PR DESCRIPTION
**Pull request by johannescpk**
Fixes #821

### CODE REVIEW

**Review by Hywan — APPROVED** [review]
I understand the patch avoids to fall in the `else` branch with a `session` set to `None`, which will avoid to return an `Err(HttpError::UserIdRequired)` (from `session`). The new path could build a request without a user ID and with `SendAccessToken::None` instead.

All of this sounds sensible to me. I don't know if it's correct though, and it could be comfortable to get a second review to validate this new flow.

cc @poljar @gnunicorn

**Review by gnunicorn — APPROVED** [review]
This is an appservice only feature, and I don't fully understand when and how the assert_identity is used by the service, but I assume you have better knowledge about that and know about the potential problems here. That said, it'd be great if 1) you could update the code docs of `ClientBuilder.assert_identity`, as they say it would fail without a session (which it wouldn't anymore now) and 2) in a PR like this you'd give a bit more context, like stating that this is an appservice only feature :) .

**Comment by johannescpk** [comment]
Thanks for the reviews and docs catch, updated accordingly.

Right, I somehow was thinking about identity assertion as independent feature - but forgot that it actually is tied to appservices only.

It's considered a bug because using the appservice crate currently will panic at runtime if you try to use it, regardless of what you try to do with it. That's because `server_versions` passes `None` as  session since a refactoring, and the `else` block always expects a session to be available. We unfortunately have no test that covers identity assertion proper for this scenario yet, which would've have surfaced it sooner.

The given PR was the only fix I found without large refactorings, because a lot depends on `Store::session` now returning `Option<&Session>` instead of `Arc<OnceCell<Session>>`.

**Comment by johannescpk** [comment]
In terms of correctness: It doesn't seem to make sense anyway to do identity assertion for endpoints that don't require authentication, since endpoints that don't require authentication don't have any knowledge about the user or session, and so wouldn't act differently either way. So maybe a refactoring including a test could take that into account.

**Comment by gnunicorn** [comment]
thanks for the clarifications!

**Pull request merged**
