### PR TITLE
Use new crates.io release of UniFFI

### PR DESCRIPTION
**Pull request by jplatte**
v0.26.0 is out! :)

### CODE REVIEW

**Comment by ganfra** [comment]
@jmartinesp is testing the release on android as there is the cleaner api for kotlin https://github.com/mozilla/uniffi-rs/pull/1869

**Comment by jmartinesp** [comment]
> @jmartinesp is testing the release on android as there is the cleaner api for kotlin [mozilla/uniffi-rs#1869](https://github.com/mozilla/uniffi-rs/pull/1869)

So far, so good. I did some testing with our app before it was released and it seemed to work fine. I'm now using the released version and I see no issues either. It should make our lives easier as Android devs by providing automatic GC, and also allow us to wrap Rust references as iOS does instead of doing `rustObject.use { KotlinObject(rustObject.copyAllValues() }`, which creates lots of overhead.

**Review by andybalaam — APPROVED** [review]

**Comment by jmartinesp** [comment]
Maybe we should also add:

```
[bindings.kotlin]
...
android_cleaner = true
```

To `bindings/matrix-sdk-ffi/uniffi.toml`? It would improve compatibility with Android APIs, allowing us to use the `SystemCleaner` in Android 33+.

**Comment by jmartinesp** [comment]
Alternatively, is there a way to provide that value locally, if we wanted to make this not android-based?

**Comment by jplatte** [comment]
Re. `android_cleaner`, I think the ideal solution would be to have different xtask commands / options for generating Kotlin code with the different possible cleaner implementations. I haven't checked yet whether that's possible, I suspect right now this can only be controlled via the config file. I wouldn't mind updating it, but I don't know what the other maintainers think. Could still be merged as a separate PR either way.

**Comment by jplatte** [comment]
Also, don't wait for me to merge on this PR. Whenever testing is done, anyone who can can press the button IMHO.

**Comment by jmartinesp** [comment]
The function that builds the Kotlin library is called `build_android_library`, so maybe we should rename that to `build_kotlin_library`, add an `is_android: bool` parameter to the command and if it's true use a custom `uniffi-android.toml` file with this value set to true (from my test, it seems like it merges its contents with the default ones). Anyway, I can probably do that in another PR if needed.

**Pull request merged**
