### PR TITLE
refactor(bindings): Use uniffi proc-macros more in sdk-ffi

### PR DESCRIPTION
**Pull request by jplatte**

### CODE REVIEW

**Review by gnunicorn — APPROVED** [review]
We still don't have a good replacement for people to discover all types and functions other than the UDL, do we? We might want to consider doing something about that...

**Comment by jplatte** [comment]
Yeah, we should discuss with the Swift & Kotlin devs.

**Comment by gnunicorn** [comment]
IMHO we can merge this first and figure out the documentation issues later.

**Comment by jplatte** [comment]
Well, we can't merge because of build issues though :)

This will probably sit unmerged for a while still, while I improve UniFFI to (a) error earlier when things wouldn't actually correctly turn into working bindings anyways and (b) to just allow more things in proc-macro land.

**Comment by jplatte** [comment]
Testing whether https://github.com/mozilla/uniffi-rs/pull/1395 works...

**Comment by jplatte** [comment]
Upstream PR is merged! 🎉

**Pull request merged**
