### PR TITLE
verification: Expose the `QrVerificationState` and the stream for its changes

### PR DESCRIPTION
**Pull request by zecakeh**
Allows to have a similar API as `SasVerification`.

### CODE REVIEW

**Review by Hywan — CHANGES_REQUESTED** [review]
Thanks for the PR. Is it possible to add tests for these new methods please?

**Comment by zecakeh** [comment]
I added a QR verification integration test (although the QR code feature doesn't seem to be counted in coverage), and added checks for `room_id()` in the SAS verification integration test.

**Comment by zecakeh** [comment]
I had to fix the fact that the `qrcode` was non-additive (used in an exhaustive enum) to fix the clippy CI job.

**Review by Hywan — APPROVED** [review]
This PR is excellent. Thanks for the great test and the documentation. I’m going to merge it 🙂.

**Pull request merged**
