### PR TITLE
ruma: Adapt to changes in ruma-client-api rc.6

### PR DESCRIPTION
**Pull request by stoically**
Currently building the sdk is broken because of changes in the latest ruma-client-api rc, this PR fixes that by adapting to the changes.

/cc @jplatte

### CODE REVIEW

**Comment by poljar** [comment]
Heh, I already have those changes locally. Still chasing some bug that somehow got introduced with regards to key queries.

**Comment by stoically** [comment]
Ah, makes sense since really active work is going on here. Feel free to close the PR then. :)

**Comment by poljar** [comment]
This one will be needed to make crypto work as well https://github.com/ruma/ruma-client-api/pull/166.

**Comment by poljar** [comment]
I'll leave it open until it's fixed, since someone might as well put in the work.

**Comment by poljar** [comment]
Fixed now, still depending on a github repo for ruma-client-api but next RC or release of it will change as well.

**Pull request closed without merging**
