### PR TITLE
chore: Release matrix-sdk version 0.9.0

### PR DESCRIPTION
**Pull request by poljar**

### CODE REVIEW

**Review by andybalaam — APPROVED** [review]
Looks good, but should we include a description of the fix I just merged? (In a changelog)

"Fix error when reading VerifiedStateOrBool with old PreviouslyVerifiedButNoLonger value"

**Comment by andybalaam** [comment]
I will create a PR with the changelog entry but free free to just include it here if it's easier

**Comment by poljar** [comment]
> I will create a PR with the changelog entry but free free to just include it here if it's easier

I'll wait for the entry and rebase.

**Comment by andybalaam** [comment]
> I'll wait for the entry and rebase.

Changelog entry PR is https://github.com/matrix-org/matrix-rust-sdk/pull/4433

**Pull request merged**
