### PR TITLE
fix(indexeddb): Fix implementation of SafeEncode for tuple of 5 elements

### LINKED ISSUE #1489: CI fails on main due to new clippy lint
It is a false positive in this case, discussion in https://github.com/rust-lang/rust-clippy/issues/10319.

### PR DESCRIPTION
**Pull request by zecakeh**
Regression introduced by merging commit 9707d73 after efdeba7.

Fixes #1489.

Signed-off-by: Kévin Commaille <zecakeh@tedomum.fr>

### CODE REVIEW

**Comment by jplatte** [comment]
Now you're running into #1489 😅

Maybe we should add some `#![allow()]`s to the affected crates.

**Comment by zecakeh** [comment]
But at least it's not my fault :stuck_out_tongue: .

> Maybe we should add some #![allow()]s to the affected crates.

Either that or we pin the rust-nightly version?

**Comment by jplatte** [comment]
… or we just wait for https://github.com/rust-lang/rust-clippy/pull/10321 before we merge. If it's merged today, that should be fine 😄

**Comment by jplatte** [comment]
If you want to sort this out now, I think I'd prefer the attributes because they're more obvious and we still get clippy upgrades even if it takes long for the attributes to be removed agian.

**Comment by zecakeh** [comment]
It's fine, I'll wait until we're tired of waiting :grin:

**Review by jplatte — APPROVED** [review]

**Pull request merged**
