### PR TITLE
chore(sdk): Move FS operation out of blocking tokio task

### PR DESCRIPTION
**Pull request by jplatte**
This should have similar or better perf as what we did before, and benefits from any instrumentation or optimizations tokio has for its async FS implementation.

This is a draft because I only updated a single place, if this direction is agreed on I will look through the other `spawn_blocking` calls to check whether they do similar things.

### CODE REVIEW

**Review by poljar — COMMENTED** [review]
The main reason why this isn't already using tokio to write the file in an async manner is that it means that the method is guaranteed to not work on WASM.

We have a abstraction in `matrix-sdk-common` to spawn tasks but not to spawn blocking things[[1]].

As for the iOS FFI case, this isn't currently helping it, since E2EE isn't enabled/working there anyways.

That being said, I agree that the current implementation is suboptimal, though not sure how to make it better without ruining WASM support.

[1]: https://github.com/matrix-org/matrix-rust-sdk/blob/main/crates/matrix-sdk-common/src/executor.rs#L18=

**Comment by jplatte** [comment]
Are fs operations supported *at all* on wasm?

**Comment by poljar** [comment]
> Are fs operations supported _at all_ on wasm?

I think so, at least on `wasm32-wasi`.

**Comment by jplatte** [comment]
Hm, alright, I guess I'll close this then.

**Pull request closed without merging**
