### PR TITLE
Unsupported ruma event types

### PR DESCRIPTION
**Pull request by DevinR528**
I really am not sure if this is the way to go about handling the events that ruma currently does not support, this would be temporary until the 0.22 version of `ruma-events` is ready.

### CODE REVIEW

**Comment by poljar** [comment]
I think that we'll want to leave this out until ruma has support for it. It adds a lot of code that would end up being removed in a couple of weeks.

**Comment by DevinR528** [comment]
Sounds good. I'd assume having an event emitter method `on_unrecognized_event(&self, Room, serde_json::Value/RawValue)` would be too permissive and against the spirit of the spec.

**Comment by poljar** [comment]
No no, custom events are a thing, so having such a method would be in the spirit of the spec.

**Comment by DevinR528** [comment]
Sweet then I can just move this into rumatui and remove it when I can!

**Comment by poljar** [comment]
This has been superseded by https://github.com/matrix-org/matrix-rust-sdk/pull/48.

**Pull request closed without merging**
