### PR TITLE
Clean up the way we build `xtask` in CI

### PR DESCRIPTION
**Pull request by richvdh**
Currently, the cache of the `xtask` binary isn't working terribly well:

 - we seem to build it on each run anyway, presumably because we don't cache any of the intermediate build artifacts. Running the binary directly rather than indirecting via "cargo" prevents this.
 - There is no sharing of the cache between the "rust" and "bindings" CI, because we use different cache keys.

This PR addresses both problems, and hopefully speeds up CI a bit as a result.

### CODE REVIEW

**Review by Hywan — COMMENTED** [review]
I salute the efforts, thank you very much!

**Review by jplatte — APPROVED** [review]
I wonder why we didn't run xtask directly before. IIRC I mostly copied the xtask caching from Ruma and there we also run xtask directly.

**Comment by jplatte** [comment]
Thanks so much for working on this by the way!

**Comment by richvdh** [comment]
I'm going to override the branch protection because codecov is broken, as per normal.

**Pull request merged**
