### PR TITLE
ci: Add a workflow to verify the minimum supported Rust version

### PR DESCRIPTION
**Pull request by andybalaam**
Fixes https://github.com/matrix-org/matrix-rust-sdk/issues/3224

Based on the recommendation at https://doc.rust-lang.org/cargo/guide/continuous-integration.html#verifying-rust-version

### CODE REVIEW

**Comment by andybalaam** [comment]
This is failing as expected since the current code requires Rust 1.76. I will merge a PR to update that before this one.

**Comment by poljar** [comment]
> This is failing as expected since the current code requires Rust 1.76. I will merge a PR to update that before this one.

Please feel free to add a commit to this PR.

**Comment by andybalaam** [comment]
> Please feel free to just add a commit to this PR.

I'd already done https://github.com/matrix-org/matrix-rust-sdk/pull/3229 , and I feel like it's marginally better as a separate PR, so...

**Comment by poljar** [comment]
> > Please feel free to just add a commit to this PR.
> 
> I'd already done #3229 , and I feel like it's marginally better as a separate PR, so...

Well it's more work, now you have to rebase this one onto main.

**Review by bnjbvr — COMMENTED** [review]
Did you run `cargo update` by mistake, or did bumping the minimum version cause a change there? It seems the `Cargo.lock` has hundreds of lines of changes...

**Comment by andybalaam** [comment]
> Did you run `cargo update` by mistake, or did bumping the minimum version cause a change there? It seems the `Cargo.lock` has hundreds of lines of changes...

I had to add a dependency, and it changed `Cargo.lock`. Not sure why...

**Comment by andybalaam** [comment]
> I had to add a dependency, and it changed `Cargo.lock`. Not sure why...

I undid the Cargo.lock changes and ran `cargo check` just to make sure, and it did it again so I am fairly sure it wasn't some kind of fat-fingers...

**Comment by bnjbvr** [comment]
Thanks for checking, and in this case please ignore me :)

(Tiny request if you're so inclined: could we use a workspace dependency for `wiremock`? Seems it's used in multiple places, and already with different versions :fearful: )

**Comment by andybalaam** [comment]
> Thanks for checking, and in this case please ignore me :)
> 
> (Tiny request if you're so inclined: could we use a workspace dependency for `wiremock`? Seems it's used in multiple places, and already with different versions 😨 )

I will do this in a different PR :+1:

**Comment by poljar** [comment]
> I am getting errors in `tests / matrix-rust-components-swift`:
> 
> ```
> Undefined symbols for architecture x86_64:
>   "_SCDynamicStoreCopyProxies", referenced from:
>       __ZN20system_configuration13dynamic_store14SCDynamicStore11get_proxies17h30fbdd908736fcfcE in libmatrix_sdk_ffi.a(system_configuration-6049f0e21ad420f1.system_configuration.97e11328e4c9ed6d-cgu.0.rcgu.o)
> ```
> 
> Any ideas why?

Revert the `reqwest` bump with `cargo update -p reqwest --precise 0.11.20`.

**Comment by andybalaam** [comment]
> (Tiny request if you're so inclined: could we use a workspace dependency for `wiremock`? Seems it's used in multiple places, and already with different versions 😨 )

https://github.com/matrix-org/matrix-rust-sdk/pull/3231

**Comment by andybalaam** [comment]
Just looking for a tick here if someone feels ready to do so.

**Review by bnjbvr — APPROVED** [review]
Thanks!

**Pull request merged**
