### PR TITLE
ci: Run cargo audit every day

### PR DESCRIPTION
**Pull request by poljar**

### CODE REVIEW

**Comment by jplatte** [comment]
I'd rather use `cargo-deny` which does a lot of other useful checks. Can send a PR tomorrow if you agree with that direction (I should have a good `deny.toml` starting point + GitHub Actions workflow lying around somewhere).

**Comment by poljar** [comment]
> I'd rather use `cargo-deny` which does a lot of other useful checks. Can send a PR tomorrow if you agree with that direction (I should have a good `deny.toml` starting point + GitHub Actions workflow lying around somewhere).

Is there some rationale for this? What else do we want that `cargo deny` does what `cargo audit` doesn't?

**Comment by jplatte** [comment]
Right, so: cargo-deny checks licenses. For users to be able to use the SDK under MIT-ish terms, our dependencies need to hqve similar licenses (i.e. no GPL or other copyleft / restrictive licenses).

cargo-deny can also be used to ban certain dependencies in the whole dep-tree. I've previously used this to ban openssl in a project that ought to be using rustls consistently. This can also be used with version ranges, i.e. we could make sure only the latest version of some crypto crates like rustls or ring is getting pulled in.

**Comment by poljar** [comment]
Ok, but are those features something we want to utilize during CI? License checks seem to be somewhat useful, but then again I already know that we're fine license-wise and checking out the license and health of a project is something I do when we introduce new ones. I'm not aware of any crate we want to ban.

`cargo-deny` requires a non-trivial configuration file, which we would need to take care of. `cargo-audit` is a trivial single purpose tool.

**Review by gnunicorn — APPROVED** [review]

**Comment by jplatte** [comment]
To be clear, I don't think we should check licenses in a scheduled CI job, just for PRs / commits. It's easy enough to run all checks on PRs, but only advisory checks on schedule:

```
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 0 * * *'

jobs:
  bans-licenses-sources:
    runs-on: ubuntu-latest
    if: github.event.name != 'schedule'

    steps:
      - uses: actions/checkout@v2
      - uses: EmbarkStudios/cargo-deny-action@v1
        with:
          command: check bans licenses sources

  advisories:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: EmbarkStudios/cargo-deny-action@v1
        with:
          command: check advisories
```

**Comment by poljar** [comment]
> To be clear, I don't think we should check licenses in a scheduled CI job, just for PRs / commits. It's easy enough to run all checks on PRs, but only advisory checks on schedule:
> 
> ```yaml
> on:
>   push:
>     branches: [main]
>   pull_request:
>     branches: [main]
>   schedule:
>     - cron: '0 0 * * *'
> 
> jobs:
>   bans-licenses-sources:
>     runs-on: ubuntu-latest
>     if: github.event.name != 'schedule'
> 
>     steps:
>       - uses: actions/checkout@v2
>       - uses: EmbarkStudios/cargo-deny-action@v1
>         with:
>           command: check bans licenses sources
> 
>   advisories:
>     runs-on: ubuntu-latest
> 
>     steps:
>       - uses: actions/checkout@v2
>       - uses: EmbarkStudios/cargo-deny-action@v1
>         with:
>           command: check advisories
> ```

I understand that, my question is, do we want any of the other features that `cargo-deny` provides at all and thus take on the burden of managing the config file for it.

**Comment by jplatte** [comment]
It has caught at least one GPL dependency at my previous job, so I think it's worthwhile. I don't think the config file is super complicated. Here is one for an open-source repo at that previous job: https://github.com/lumeohq/lumeo-types-rs/blob/a26720467cb8bf8cf0dbdf37063ddb136751072e/deny.toml

It is 66 lines long, but more than half of that is comments or newlines.

**Comment by poljar** [comment]
> It has caught at least one GPL dependency at my previous job, so I think it's worthwhile. I don't think the config file is super complicated. Here is one for an open-source repo at that previous job: https://github.com/lumeohq/lumeo-types-rs/blob/a26720467cb8bf8cf0dbdf37063ddb136751072e/deny.toml
> 
> It is 66 lines long, but more than half of that is comments or newlines.

Eh, I guess. Though adding this does not mean that we can just accept dependencies without looking at the general project health.

I was looking for a reason to adopt `cargo-deny` for vodozemac but I don't think I found one. If you feel strongly about this I'm fine with going the `cargo-deny` route, though I prefer `cargo-audit` for the simplicity.

**Pull request merged**
