### PR TITLE
chore: Bump the Ruma revision

### PR DESCRIPTION
**Pull request by poljar**

### CODE REVIEW

**Comment by toger5** [comment]
Ci fails. This makes sense since the ruma change contains breaking changes for the widget api (in the rust sdk)
So those issues will go away once we merge the related rust-sdk PR: https://github.com/matrix-org/matrix-rust-sdk/pull/3763

**Comment by poljar** [comment]
> Ci fails. This makes sense since the ruma change contains breaking changes for the widget api (in the rust sdk) So those issues will go away once we merge the related rust-sdk PR: #3763

Oh, in that case, the Ruma bump needs to be part of you PR.

**Comment by toger5** [comment]
So I just copy the ruma hash you included here.

**Comment by poljar** [comment]
> So I just copy the ruma hash you included here.

Yup, don't forget to run `cargo check` so the lockfile gets updated as well. You can probably just cherry-pick the patch as well.

**Pull request closed without merging**
