### PR TITLE
Update ruma to rev d6aa37c848b7f682a98c25b346899e284ffc6df7

### PR DESCRIPTION
**Pull request by jsparber**
We need the new version to get the fix for https://github.com/ruma/ruma/issues/380

### CODE REVIEW

**Review by poljar — CHANGES_REQUESTED** [review]
Wasn't the `unstable-synapse-quirks` feature renamed to `compat` over [here](https://github.com/ruma/ruma/commit/891db9083ba520608255f5febc2183af4df5fa5f).

We should change this if we're bumping Ruma versions as well.

**Comment by jsparber** [comment]
not reallu sure, @jplatte probably knows better

**Comment by jplatte** [comment]
> Wasn't the `unstable-synapse-quirks` feature renamed to `compat` over [here](https://github.com/ruma/ruma/commit/891db9083ba520608255f5febc2183af4df5fa5f).

Kind of, but not really. The `compat` feature is only for things that strictly increase compatibility. At the time I decided to introduce it, there was only one use of `feature = "unstable-synapse-quirks"` outside of this category and when I looked into it, it turned out the spec had been updated to match synapse's behaviour. The authentication thing however doesn't fit this category either, because if it was applied server-side, say in Conduit¹, Conduit would suddenly start requiring authentication from users from these endpoints.

So all in all: Just activate both features 🙂  
You can decide whether you want to make `compat` optional like `unstable-synapse-quirks`. It does result in deserialization behaviour that one might consider unintuitive, but I plan to at least document that until ruma 0.1.0 (ruma/ruma#404).

**Comment by poljar** [comment]
I guess it's fine to just enable `compat` all the time.

**Comment by jsparber** [comment]
how should we progress with this?

**Comment by poljar** [comment]
> how should we progress with this?

Sorry if it wasn't clear. Lets leave `unstable-synapse-quirks` as is and enable `compat` unconditionally.

**Comment by jsparber** [comment]
@poljar i enabled `compat` for ruma.

**Pull request merged**
