### PR TITLE
crypto ffi: use a u64 for timestamps instead of a String

### PR DESCRIPTION
**Pull request by bnjbvr**
And also comment that the timestamp is in seconds since the epoch.

Also silence a warning about unneeded qualifications.

### CODE REVIEW

**Comment by bnjbvr** [comment]
cc @matrix-org/rust-sdk-wasm-reviewers since this is a breaking change to the public API of the FFI

**Comment by bnjbvr** [comment]
cc @bmarty @ganfra would this cause issues that we changed the format on the legacy Android app?

**Comment by richvdh** [comment]
cc @BillCarsonFr

**Review by Hywan — APPROVED** [review]

**Comment by bmarty** [comment]
> cc @bmarty @ganfra would this cause issues that we changed the format on the legacy Android app?

I guess it the type is changing from String to Long we will have an API break, but it should not cause issue since it will be detected at compile time.

**Pull request merged**
