### PR TITLE
Compile for Mac Catalyst

### PR DESCRIPTION
**Pull request by bmisiak**
Hello!
Trying to port Element X to Mac Catalyst. The Rust SDK is of course a prerequisite.

Unfortunately, there is a problem with rustc, so I wrote up a pull request to fix it there first:
https://github.com/rust-lang/rust/pull/111384

After it gets merged, the changes I made here to `build_crypto_xcframework.sh` will make it compile for Catalyst and bundle all four platforms (iOS, macOS, Catalyst and simulator) into one .xcframework.

It will use nightly rustc for catalyst, but stable for the other platforms.

### CODE REVIEW

**Comment by stefanceriu** [comment]
This is really exciting, just one note thought: nowadays the old bash script ElementX used is gone. `build_crypto_xcframework.sh` is only used for the crypto part, exposing it to the old Element app.

Instead of that, Element X uses an xtask now https://github.com/matrix-org/matrix-rust-sdk/blob/main/xtask/src/swift.rs#L126

Also fwiw:
this is where I dropped the original catalyst support https://github.com/matrix-org/matrix-rust-sdk/commit/c10961f06847fa315bc6c00170e26afb94a48d71

and this is how we actually use the xtask when releasing the sdk https://github.com/matrix-org/matrix-rust-components-swift/blob/main/Tools/Scripts/release.py

**Comment by bmisiak** [comment]
Excellent, thank you, I'll adjust it as well before removing the draft
status.

**Comment by bmisiak** [comment]
Thanks @stefanceriu, my changes to rustc were merged and matrix-rust-sdk can now create the xcframework for Catalyst. I updated the xtask.
I had to upgrade `log` because its previous version was pulling in an alpha version of `value-bag`, which broke on nightly rustc.

**Review by stefanceriu — CHANGES_REQUESTED** [review]
I just tested this for ElementX and it works great, everything gets build properly and can be used through normal methods.

The bad news is that ElementX now uses MapBox which doesn't provide catalyst support so even if we build the SDK for it we can't use it. The only thing we'll get is longer builds times.

I think what we should do is put the catalyst targets under flag and not build them by default.

As for the Crypto script, that's only used by old Element and we probably shouldn't even bother changing it and potentially adding bugs.

**Comment by jplatte** [comment]
Hey, we discussed this again today. Unfortunately, we don't really have the capacity to support it "officially". We're still happy to receive catalyst-related bug fixes, or attempt to help users who use that build target, but adding it to our build scripts would imply that we actually test that it works. I hope it's not too much trouble for you to maintain your own build script separately.

**Pull request closed without merging**
