### PR TITLE
Start using UniFFI async support

### PR DESCRIPTION
**Pull request by jplatte**
#1587 again, but rebased.

### CODE REVIEW

**Comment by Hywan** [comment]
Maybe the crash with `tracing` is solved now. Let's see.

**Comment by stefanceriu** [comment]
Sorry folks, getting a similar crash:

```
thread '<unnamed>' panicked at 'tried to clone Id(2253998836940828), but no span exists with that ID
This may be caused by consuming a parent span (`parent: span`) rather than borrowing it (`parent: &span`).', /Users/stefanceriu/.cargo/registry/src/github.com-1ecc6299db9ec823/tracing-subscriber-0.3.16/src/registry/sharded.rs:311:32
...
2023-03-20T11:30:49.978259Z ERROR uniffi_core::ffi::rustcalls: Caught a panic calling rust code: "tried to clone Id(2253998836940828), but no span exists with that ID\nThis may be caused by consuming a parent span (`parent: span`) rather than borrowing it (`parent: &span`)."    
MatrixRustSDK/matrix_sdk_ffi.swift:3833: Fatal error: 'try!' expression unexpectedly raised an error: MatrixRustSDK.(unknown context at $107e41c30).UniffiInternalError.rustPanic("tried to clone Id(2253998836940828), but no span exists with that ID\nThis may be caused by consuming a parent span (`parent: span`) rather than borrowing it (`parent: &span`).")
2023-03-20 13:30:49.979624+0200 ElementX[30215:226559] MatrixRustSDK/matrix_sdk_ffi.swift:3833: Fatal error: 'try!' expression unexpectedly raised an error: MatrixRustSDK.(unknown context at $107e41c30).UniffiInternalError.rustPanic("tried to clone Id(2253998836940828), but no span exists with that ID\nThis may be caused by consuming a parent span (`parent: span`) rather than borrowing it (`parent: &span`).")

```

**Comment by stefanceriu** [comment]
Update on this: I completely disabled rust side tracing in ElementX and I can't get it to crash anymore. I also found a workaround swift side by dispatching the `latestRoomMessage` call to a different queue:

```
- if let latestRoomMessage = await room.latestRoomMessage() {
+ if let latestRoomMessage = await Task.detached(priority: .high) { await room.latestRoomMessage() }.value {
```

How can we go about finding out what's wrong with tracing?

**Comment by poljar** [comment]
If we take a look at the message:
> 2023-03-20T11:30:49.978259Z ERROR uniffi_core::ffi::rustcalls: Caught a panic calling rust code: "tried to clone Id(2253998836940828), but no span exists with that ID\nThis may be caused by consuming a parent span (`parent: span`) rather than borrowing it (`parent: &span`)."    

The message means that we're trying to log a message inside a span where the parent span has been already dropped.

Suppose we have two methods that create a span:

```rust
#[instrument]
async fn bar() {
    sleep(1).await
    trace!("Hello bar")
    sleep(1).await
}

#[instrument]
async fn foo() {
     sleep(1).await
     foo().await;
     trace!("Hello foo");
    sleep(1).await
}
```

So we have two spans, the "foo" span and the "bar" span. `foo()` calls `bar()` so the "foo" span is the parent of the "bar" span. And the trace call `trace!("Hello bar")` will try to access the parent span to annotate the log message correctly.

But the parent span seems to be gone. It seems that we're dropping the `foo` span too early. 

The workaround you posted suggests that, changing the queue where the code will get executed likely changes the order in which things get dropped as well.

Now the span isn't dropped and everything seems to be fine.

**Comment by jplatte** [comment]
I have an idea on how to debug this… Investigating.

**Comment by jplatte** [comment]
@stefanceriu This is ready for another test run. I've included https://github.com/mozilla/uniffi-rs/pull/1515, which revamps how the async support works under the hood, so there's a good chance it will fix our crashes.

**Review by bnjbvr — APPROVED** [review]
Looks good in principle, cc @Hywan in case you want to take a look too.

**Comment by jplatte** [comment]
@stefanceriu *Now* it's ready for another test run!

**Comment by stefanceriu** [comment]
I tested this out today and couldn't find any more crashes but I would still like to test it more. Let's please wait to merge this until after the next ElementX public release goes out.

**Comment by Hywan** [comment]
Eager to know the output of your testing session.

**Pull request merged**
