### PR TITLE
feat(room list service): enable read receipts for subscribed rooms

### PR DESCRIPTION
**Pull request by bnjbvr**
This does what it says on the tin. cc @stefanceriu

### CODE REVIEW

**Comment by jplatte** [comment]
I remember recently bumping Ruma locally, and it was more work. CI agrees 😅

**Comment by jplatte** [comment]
#2481

**Comment by Hywan** [comment]
Closed in favor of https://github.com/matrix-org/matrix-rust-sdk/pull/2481.

**Comment by stefanceriu** [comment]
#2481 is not enough, we need those `with_receipt_extension` changes

**Comment by jplatte** [comment]
Yeah, this should just be rebased now that the other PR is merged.

**Comment by bnjbvr** [comment]
This has been rebased, thanks @jplatte for the proper Ruma update.

**Review by Hywan — APPROVED** [review]
It looks good to me.

**Pull request merged**
