### PR TITLE
crypto: Implemented sharing room keys for past messages (MSC3061) 

### LINKED ISSUE #580: Implement MSC3061: Sharing room keys for past messages
From element-ios created by [manuroe](https://github.com/manuroe): vector-im/element-ios#4947  

As per [MSC3061](https://github.com/matrix-org/matrix-doc/pull/3061)

See https://github.com/vector-im/element-android/issues/4153

### PR DESCRIPTION
**Pull request by Michael-Hollister**
Fixes #580 

## Overview

I have created an implementation for MSC 3061 and wanted to share the changes should the team want to merge into the SDK. 

Note this follows the implementation suggested in the MSC where keys are forwarded upon invitation of a new user. Based on past discussion in https://github.com/matrix-org/matrix-rust-sdk/issues/580 however, this approach was was not preferred due to some flaws. I thought I would still share this implementation however for the following reasons:
1.  MSC 3061 has officially been merged into the spec per my understanding: https://github.com/matrix-org/matrix-spec-proposals/pull/3061
2. The proposed changes discussed in https://github.com/matrix-org/matrix-rust-sdk/issues/580 sounded to me that it requires a new MSC proposal for adding a new event type and improving the key sharing process.
3. This implementation provides a working solution that is equivalent to what is offered currently in the other Matrix SDKs, which can be used until the preferred solution is developed.

Any feedback welcome.

## PR Dependencies:
* ~vodozemac: https://github.com/matrix-org/vodozemac/pull/114~
* ruma: https://github.com/ruma/ruma/pull/1669

## Testing:

Tested key sharing with verified and unverified devices with multiple clients including:
- FUTO Circles iOS / Android
- iamb
-  Element / Cinny (interoperability testing since these don't use the crypto FFI)

## Todo:
- [x] Update Cargo.toml to point to upstream SDK instead of fork with the ruma/~vodozemac~ changes
- [ ] Docs: Update room key sharing  diagram indicating how `HistoryVisibility` is taken into account when sharing keys (https://raw.githubusercontent.com/matrix-org/matrix-rust-sdk/main/contrib/key-sharing-algorithm/model.png)
- [ ] Build and deploy a new crypto FFI release?
- [ ] Public API changes documented in changelogs (optional)

Signed-off-by: Michael Hollister <michael@futo.org>

### CODE REVIEW

**Comment by poljar** [comment]
To manage expectations a bit, I sadly won't have the time to take a proper look at this before the end of the month.

**Comment by Michael-Hollister** [comment]
> To manage expectations a bit, I sadly won't have the time to take a proper look at this before the end of the month.

No problem, thanks for letting me know and taking the time to review this when ready.

**Comment by Michael-Hollister** [comment]
If this PR is of interest being reviewed/merged, let me know and I can fix conflicts and push a few fixes to issues that exist in this old version. Otherwise, my impression from the discussion in https://github.com/matrix-org/matrix-spec/pull/1655 is that the PR will be not be merged, so I will be holding off updating until needed.

**Comment by poljar** [comment]
The MSC has now been rejected, more info here: https://github.com/matrix-org/matrix-spec-proposals/pull/3061#issuecomment-2414282902.

Closing.

**Pull request closed without merging**
