### PR TITLE
WASM support

### PR DESCRIPTION
**Pull request by stoically**
This starts support for compiling to the wasm32-unknown-unknown webassembly target.

- [x] Find solution to handle sleeping
- [x] Handle User-Agent correctly with regards to CORS restrictions
- [x] Try to get encryption to work
- [ ] ~~Try to get  tests working as is~~: Doesn't work because of reliance on either mockito (tcplistener) or filesystem
- [x] Try to get the tests that rely on filesystem working by inlining the json files
- [x] Add wasm target build to travis
- [ ] `cjson` changes
  - [x] File PR: https://github.com/engineerd/cjson/pull/1
  - [ ] Merged
- [x] `libolm` changes
  - [x] Send PR per mail
  - [x] [Merged](https://gitlab.matrix.org/matrix-org/olm/-/commit/611d3949cb06447e4281a543957bf877fe074eed)
- [ ] `olm-sys` changes
  - [x] File PR: [BrainBlasted/olm-sys#8](https://gitlab.gnome.org/BrainBlasted/olm-sys/-/merge_requests/8)
  - [ ] Merged

To run the example in ` matrix_sdk/examples/wasm_send_message`

- Install [emscripten](https://github.com/emscripten-core/emscripten) and make it available on PATH
- Adjust credentials and room id in `src/lib.js`
- npm install
- npm run serve
- Visit http://localhost:8080
- Should send an message to the room

### CODE REVIEW

**Comment by poljar** [comment]
I renamed the types subproject now to matrix-sdk-common. The locks should go in there, and anything that's shared between the different crates to make wasm work.

**Comment by stoically** [comment]
While trying to get encryption to work I hit the roadblock that libolm requires the `cstddef` (c++'s stdlib). The `wasm32-unknown-unknown` target doesn't provide stdlib's, so that won't work. 

I've tried to work around that by compiling just `olm-sys` with `emcc` in its `build.rs`, but that seems to not work.

Another alternative would be to try to compile against the `wasm32-unknown-emscripten` target, but unfortunately only [`stdweb`](https://github.com/koute/stdweb) supports emscripten, while [`wasm-bindgen`](https://github.com/rustwasm/wasm-bindgen/) does not. It seems that the Rust ecosystem is moving away from `stdweb` and emscripten, so I'm not sure it makes sense to put in the work to support that - but I'm not sure either what an viable alternative could be.

**Comment by poljar** [comment]
> While trying to get encryption to work I hit the roadblock that libolm requires the `cstddef` (c++'s stdlib). The `wasm32-unknown-unknown` target doesn't provide stdlib's, so that won't work.
> 
> I've tried to work around that by compiling just `olm-sys` with `emcc` in its `build.rs`, but that seems to not work either.
> 
> Another alternative would be to try to compile against the `wasm32-unknown-emscripten` target, but unfortunately only [`stdweb`](https://github.com/koute/stdweb) supports emscripten, while [`wasm-bindgen`](https://github.com/rustwasm/wasm-bindgen/) does not. It seems that the Rust ecosystem is moving away from `stdweb` (last commit to the repo over 6 months ago) and emscripten, so I'm not sure it makes sense to put in the work to support that - but I'm not sure either what an viable alternative could be.

That's a shame, perhaps asking at the wasm-bindgen repo or wasm-pack repo would give us some answers if this will ever be possible.

**Comment by stoically** [comment]
Turns out I was wrong. It _is_ possible to compile an archive with emscripten and use it with the `wasm32-unknown-unknown` target, yay.

**Comment by stoically** [comment]
Thanks for the quick and thorough review. I've made the requested changes and a small fix regarding a missing `continue`. The git dep for the `futures-locks` crate is required since it includes an refactoring to std futures.

I've opened an tracking ticket for the remaining issues here: https://github.com/matrix-org/matrix-rust-sdk/issues/35

**Comment by poljar** [comment]
Ah ok, since futures-locks is only used for wasm I think I'm going to merge this as is. Btw that one commit message is a bit misleading, encryption does work under wasm if the deps are set to the git repos.

**Comment by stoically** [comment]
Removed the misleading comment in the commit message.

> Ah ok, since futures-locks is only used for wasm I think I'm going to merge this as is. 

Sounds good to me, thanks!

**Pull request merged**
