### PR TITLE
chore(cargo) Update dependencies

### PR DESCRIPTION
**Pull request by Hywan**
As the title says!

This PR updates the dependencies. It also removes `cfg_vis` from `matrix-rust-sdk` because that's pretty useless if I understand what it was supposed to do. It was also introducing more proc-macros and a duplicated dep with Ruma.

### CODE REVIEW

**Review by poljar — APPROVED** [review]
Looks fine, but what was `cfg_vis` supposed to do? Hide the method on WASM, why?

**Comment by Hywan** [comment]
I don't know. The default is `pub` so we cannot have any warning or whatever.

**Comment by poljar** [comment]
This should now be fine to merge since #3380 landed?

**Comment by zecakeh** [comment]
You'll need to update the version of nightly used in CI if you want to upgrade axum.

**Pull request merged**
