### PR TITLE
Optimising the DB Search

### PR DESCRIPTION
**Pull request by ANIR1604**
# Advantages : 

- Fixes : #4337 
- Instead of calling object_store and get separately in different lines, the code groups them together in a single chain. This makes the code more concise and improves readability.
- The ? operator is used after each method to propagate errors immediately if any of the calls fail, avoiding unnecessary logic or nesting.
- We avoid multiple method calls and unnecessary intermediate variables. The result of get() is directly assigned, which will later be handled by the map() and transpose() methods.

### CODE REVIEW

**Comment by ANIR1604** [comment]
> Thanks for the patch, but I don't see how it changes anything to the actual code.

Actually this PR is improving the readability and the error handling of the process which somewhat improving its optimization. 

We can use Cache Memory by Hashmaps to improve the DB calls should I go with that method ?

**Comment by Hywan** [comment]
> Actually this PR is improving the readability and the error handling of the process which somewhat improving its optimization.

I need proof of that. Readibility, yes, a bit, but I'm not sure it improves optimization from the compiler. From the compiler point of view, once reduced to a simple form, there is no difference between the two versions.

**Comment by ANIR1604** [comment]
> > Actually this PR is improving the readability and the error handling of the process which somewhat improving its optimization.
> 
> I need proof of that. Readibility, yes, a bit, but I'm not sure it improves optimization from the compiler. From the compiler point of view, once reduced to a simple form, there is no difference between the two versions.

Sir Can I use Cache Hashmaps to improve optimization ?

**Comment by Hywan** [comment]
You can try for sure. I cannot merge this PR since it doesn't do anything useful and clearly not what the description claims.

**Pull request closed without merging**
