### PR TITLE
refactor(crypto): Introduce a signalling mutex

### PR DESCRIPTION
**Pull request by poljar**

### CODE REVIEW

**Review by gnunicorn — COMMENTED** [review]
I don't understand. Isn't this what `Mutuable<T>` already is by itself? If you call [`mutable.lock_mut()`](https://docs.rs/futures-signals/latest/src/futures_signals/signal/mutable.rs.html#316) you get `MutableLockMut` that will track whether the inner has changed and fires a signal if it did. Why have another Mutex next to it in this util wrapper?

**Comment by poljar** [comment]
> I don't understand. Isn't this what `Mutuable<T>` already is by itself? If you call [`mutable.lock_mut()`](https://docs.rs/futures-signals/latest/src/futures_signals/signal/mutable.rs.html#316) you get `MutableLockMut` that will track whether the inner has changed and fires a signal if it did. Why have another Mutex next to it in this util wrapper?

Because `T` and `S` are not the same type, the SAS verifications has a lot of states while the user cares only about a subset of those states.

We have a Mutex over `T` (`InnerSas`) but want to fire out signals of `S` (`SasState`). We can transform `InnerSas` into `SasState` using a `From` implementation.

**Comment by gnunicorn** [comment]
But then the from and a
```
mutuable.signal().map(|e| e.into())
```

would be sufficient, no?

**Comment by poljar** [comment]
> But then the `from` and a
> 
> ```
> mutuable.signal().map(|e| e.into())
> ```
> 
> (with the appropriate type declaration) would be sufficient, no?

Indeed, I guess I didn't trust `Mutable` enough to fully replace our `Mutex` for the `inner` field.

**Review by gnunicorn — APPROVED** [review]
lgtm

**Pull request merged**
