### PR TITLE
Upgrade http, ruma, reqwest and wiremock dependencies

### PR DESCRIPTION
**Pull request by zecakeh**
They need to be updated together because the latters depend on the former.

matrix-authentication-service is still using http 0.2 so we need to add a conversion layer between both major versions for OIDC requests for now.

We need to update vodozemac too because of a dependency resolution issue.

### CODE REVIEW

**Review by bnjbvr — COMMENTED** [review]
I'd prefer that we'd wait for the matrix-authentication-service crate to update its HTTP crate instead of adding all the HttpOld/HttpNew conversation stuff.

Out of curiosity: are you making this PR because you require it for some reasons, or is it only careful maintenance? (in any case, thanks for opening such a PR!)

**Review by bnjbvr — APPROVED** [review]
Actually it's a nice step forward as it removes a bunch of duplicated crates in the dependency tree, and we can easily get rid of the http_old conversion code later on. Thanks!

**Comment by poljar** [comment]
> Actually it's a nice step forward as it removes a bunch of duplicated crates in the dependency tree, and we can easily get rid of the http_old conversion code later on. Thanks!

For reference, I looked into updating MAS itself, but it's blocked by https://github.com/open-telemetry/opentelemetry-rust/pull/1674 getting merged and released.

**Comment by zecakeh** [comment]
> Out of curiosity: are you making this PR because you require it for some reasons, or is it only careful maintenance? (in any case, thanks for opening such a PR!)

No we don't require it for the moment, I just knew it was probably going to be a big change, so I wanted to get a head start.

> For reference, I looked into updating MAS itself, but it's blocked by https://github.com/open-telemetry/opentelemetry-rust/pull/1674 getting merged and released.

Yeah we have been waiting a bit to update http in Ruma so we could avoid the conversion layer for the SDK, but we would like to make a new release soon and we wanted to upgrade http before it.

**Comment by zecakeh** [comment]
Merged main branch to resolve conflict

**Pull request merged**
