### PR TITLE
Disable debug-info for the dev profile

### PR DESCRIPTION
**Pull request by jplatte**
Let's see whether this shows up in CI times..

### CODE REVIEW

**Comment by poljar** [comment]
Looking at the times, still 30 minutes for the Apple tests. I would leave debug info in if it doesn't help in any way.

**Comment by jplatte** [comment]
I think I still want to get back to this. For Ruma it was a >10% improvement for test running time. I'll test locally soon, where numbers are more reliable.

**Comment by jplatte** [comment]
This is a pretty substantial win locally. I benchmarked `cargo clean && cargo check` as well as `cargo clean && cargo build` and also compared `target` directory sizes.

| _           | w/ debug | w/o debug | 
|-------------|----------|-----------| 
| Check 1     | 41.60s   | 37.92s    | 
| Check 2     | 41.40s   | 38.03s    | 
| Target Size | 1.2G     | 822M      | 
| Build 1     | 57.09s   | 49.08s    | 
| Build 2     | 57.90s   | 50.43s    | 
| Target Size | 3.1G     | 1.5G      | 

Basic system metadata:

* Processor: AMD Ryzen 5 3600
* RAM: 16GB DDR4 2400MHz
* Disk: Samsung SSD 860 EVO 1TB (SATA III)

**Review by poljar — APPROVED** [review]
I tried to reproduce the `cargo check` times and they are within 1s.

Not completely convinced but let's merge this since I can't remember when I had to use a debugger with the rust-sdk.

**Pull request merged**
