### PR TITLE
Enable the future_not_send lint in our main crates

### PR DESCRIPTION
**Pull request by poljar**
Please note that this excludes the matrix-sdk-crypto crate, this crate uses generic functions in a bunch of places without having a Send bound.

We would either need to add a bound or add exceptions for them.

### CODE REVIEW

**Comment by jplatte** [comment]
I wanted to do this previously, but it fails for generic functions. Upstream issue: https://github.com/rust-lang/rust-clippy/issues/6947

**Comment by poljar** [comment]
> I wanted to do this previously, but it fails for generic functions. Upstream issue: [rust-lang/rust-clippy#6947](https://github.com/rust-lang/rust-clippy/issues/6947)

I know: https://github.com/matrix-org/matrix-rust-sdk/issues/935#issuecomment-1923755909

**Comment by jplatte** [comment]
Yeah, saw the issue comment after this PR ^^

**Review by Hywan — APPROVED** [review]
OK to me too.

**Comment by poljar** [comment]
Hmm, this has a lot of things. Will come back to this later.

**Pull request closed without merging**
