### PR TITLE
ui: Take a `PathBuf` to send an attachment

### PR DESCRIPTION
**Pull request by zecakeh**
I found the previous API confusing. Firstly, the parameter name was "filename" when we want a file path. Secondly, we take a `String` when we want a `Path` (or `PathBuf` to get an owned value here).

- [x] Public API changes documented in changelogs (optional)

### CODE REVIEW

**Review by poljar — APPROVED** [review]
Indeed, this makes more sense.

**Review by Hywan — APPROVED** [review]
Good to me too. Can you rebase on top of `main` please, before merging?

**Comment by zecakeh** [comment]
I merge it actually. Do you prefer a rebase?

**Comment by zecakeh** [comment]
For info, the auto-merge here has failed.

**Pull request merged**
