### PR TITLE
Change upload to take &[u8]

### PR DESCRIPTION
**Pull request by jplatte**
Just opening this to hear whether I should continue removing `Read` everywhere or it should be kept in `matrix-sdk-crypto`.

### CODE REVIEW

**Comment by poljar** [comment]
> 

Which parts in `matrix-sdk-crypto` specifically?

**Comment by jplatte** [comment]
Okay, having actually gone through it all now, no change is really *required* for `-crypto`, but because I had already done it this PR now contains a change from `impl Read` to `&[u8]` for `AttachmentEncryptor`. I think we should either revert that, or do the same thing to `AttachmentDecryptor`, before merging. Wdyt?

**Comment by poljar** [comment]
> Okay, having actually gone through it all now, no change is really _required_ for `-crypto`, but because I had already done it this PR still contains a change from `impl Read` to `&[u8]` for `AttachmentEncryptor`. I think we should either revert that, or do the same thing to `AttachmentDecryptor`, before merging. Wdyt?

I think `AttachmentDecryptor` and `AttachmentEncryptor` are fine to use a `Reader`, you can always use a `Cursor` and there's nothing wrong with it.

Callers, if they want, can turn this into async code via `spawn_blocking()` but a CLI tool that encrypts/decrypts attachments might as well block.

So let's revert that.

**Comment by jplatte** [comment]
Done, also rewrote the first commit message accordingly.

**Review by poljar — APPROVED** [review]

**Pull request merged**
