### PR TITLE
State key fix

### LINKED ISSUE #6: Merge RoomMember and User structs.
Currently we have two structs for room members, `User` and `RoomMember`, they both have a events field and `RoomMember` has a field that holds a `User` struct.

It would probably make sense to remove the duplicate fields and just merge `User` into `RoomMember`.

### PR DESCRIPTION
**Pull request by DevinR528**
Resolves #6 

I also found that when a `m.room.power_levels` event came (from the actual matrix server) making the `UserId` from the `state_key` failed. I made a note of it in `Room::handle_power_level`.

### CODE REVIEW

**Comment by poljar** [comment]
A state key can be an empty string so I think parsing it as a UserId will fail in this case.

**Comment by DevinR528** [comment]
should that event use the `UserId`?

**Comment by poljar** [comment]
> should that event use the `UserId`? or if the parse failed then use the `UserId`

Not sure what you mean, could you clarify?

**Comment by DevinR528** [comment]
Ahh yea sorry

```rust
pub fn handle_power_level(&mut self, event: &PowerLevelsEvent) -> bool {
    // when getting a response from the actual matrix server `state_key`
    // was empty, the spec says "state_key: A zero-length string."
    // for `m.room.power_levels` events
    let user = if let Ok(id) = UserId::try_from(event.state_key.as_str()) {
        id
    } else {
        return false;
    };
    if let Some(member) = self.members.get_mut(&user) {
        member.update_power(event)
    } else {
        false
    }
}
```
if this `try_from` fails should we use `event.sender` or just use `event.sender` in this case.
[the spec just incase](https://matrix.org/docs/spec/client_server/r0.5.0#m-room-power-levels)

**Comment by poljar** [comment]
The spec tells us that the state key will be a zero length, or empty, string for power levels.

The sender tells us who changed the power level. To find the power level for a specific user we need to look into the [content.users](https://docs.rs/ruma-events/0.18.0/ruma_events/room/power_levels/struct.PowerLevelsEventContent.html#structfield.users) hashmap.

**Comment by DevinR528** [comment]
Ok I think I'm getting it, so this event won't update a user at all. Our `Room` needs to have a power_level field and that's what would be updated?

**Comment by poljar** [comment]
> Ok I think I'm getting it, so this event should check for an update in the `content.users` hashmap but otherwise our `Room` should have power level fields on it since this event is more of a room state change?

Correct, the room has default power levels and then the `content.users` map has exact settings for specific users.

**Pull request merged**
