### PR TITLE
Make event handler futures non-Send on wasm

### PR DESCRIPTION
**Pull request by jplatte**

### CODE REVIEW

**Comment by jplatte** [comment]
I initially named the new traits `TraitUnlessWasm`, but then switched to `TraitOutsideWasm`. I'm not super happy with either, alternative name suggestions are very welcome ^^

**Comment by docweirdo** [comment]
`TraitGapWasm`?

**Review by poljar — APPROVED** [review]
I was letting this simmer for a bit in the hope that I would come up with a better name but sadly fell short.

Looks good.

**Comment by jplatte** [comment]
> `TraitGapWasm`?

Thanks for the suggestion but I think it's not very clear. I'll merge with the current naming.

**Pull request merged**
