### PR TITLE
MSC3700: Ignore `content.sender_key`

### PR DESCRIPTION
**Pull request by erikjohnston**
This is an implementation of [MSC3700](https://github.com/matrix-org/matrix-doc/pull/3700) to demonstrate that the MSC is viable.

This PR changes `CrytpoStore` in a non-backwards compatible way, so would need a version bump if we were to land it.

### CODE REVIEW

**Review by poljar — CHANGES_REQUESTED** [review]
This looks sensible but two things:
1. Serialization will fail if the `sender_key` is missing, we need a Ruma change for this for the [MegolmV1AesSha2Content]
2. Since we now somewhat ship Element R and Fractal-Next has a steady flow of test flatpaks we do migrations of the store. I'm afraid that this will need a migration path over [here](https://github.com/matrix-org/matrix-rust-sdk/blob/59d21d9683cd83196b6b4de6c605fb611d20d384/crates/matrix-sdk-crypto/src/store/sled.rs#L272)

[MegolmV1AesSha2Content]: https://docs.ruma.io/ruma_events/room/encrypted/struct.MegolmV1AesSha2Content.html

**Comment by erikjohnston** [comment]
> * Serialization will fail if the `sender_key` is missing, we need a Ruma change for this for the [MegolmV1AesSha2Content](https://docs.ruma.io/ruma_events/room/encrypted/struct.MegolmV1AesSha2Content.html)

ATM everything should still be adding `sender_key`, just not reading it, so it should be fiiiiiiine (ish) for now. Though absolutely yes, will need to change the Ruma struct if MSC3700 lands.

**Comment by jplatte** [comment]
Since MSC3700 says that it still must be sent, I'm pretty certain this does not require changes in Ruma (we did add a deprecation notice under an unstable MSC feature flag, but that's all I see we can do there).

This just need to be made backwards-compatible w.r.t. the serialized stuff in the store, then it should be fine (is what I think we discussed a few weeks ago).

**Comment by erikjohnston** [comment]
Closing this as I think this is in hand elsewhere?

**Comment by richvdh** [comment]
> Closing this as I think this is in hand elsewhere?

(It was superceded by https://github.com/matrix-org/matrix-rust-sdk)

**Pull request closed without merging**
