### PR TITLE
refactor(crypto)!: Remove unused `OneTimeKey::Key` and `SessionCreationError::OneTimeKeyUnknown` variants

### PR DESCRIPTION
**Pull request by zecakeh**
As discussed in https://github.com/matrix-org/matrix-rust-sdk/pull/4171#discussion_r1820767666.

### CODE REVIEW

**Review by poljar — APPROVED** [review]
Looks good, though the commit mentions that `OneTimeKey::Signed` was removed, no such variant exists and `SignedKey` certainly was not removed.

**Comment by zecakeh** [comment]
Oops, sorry about that. It's fixed now.

**Review by poljar — APPROVED** [review]

**Comment by andybalaam** [comment]
> This contained some crypto interface changes ([matrix-org/matrix-rust-sdk-crypto-wasm/actions/runs/11604714936/job/32313920920](https://github.com/matrix-org/matrix-rust-sdk-crypto-wasm/actions/runs/11604714936/job/32313920920)) that would have been helpful to document in the [changelog](https://github.com/matrix-org/matrix-rust-sdk/blob/main/crates/matrix-sdk-crypto/CHANGELOG.md)

No blame though - it's almost impossible to keep track of this and the automated checks we have are after-the-fact, which is how I'm picking it up.

**Comment by poljar** [comment]
> This contained some crypto interface changes (https://github.com/matrix-org/matrix-rust-sdk-crypto-wasm/actions/runs/11604714936/job/32313920920) that would have been helpful to document in the [changelog](https://github.com/matrix-org/matrix-rust-sdk/blob/main/crates/matrix-sdk-crypto/CHANGELOG.md)

Err, but we're using `git-cliff` for changelogs and this commit is even marked to contain a breaking change.

**Comment by poljar** [comment]
To clarify a bit further, every time you bump the SDK version in the WASM bindings you can use `git cliff $commit..range` to get the list of relevant changes. So no need to manually look through the `CHANGELOG.md` file and guestimate what was part of your bump or not.

Of course all of this might become even easier once we start doing releases, hopefully next week.

**Comment by andybalaam** [comment]
Ah, so I should not have expected it to appear in `CHANGELOG.md` yet? Thanks, I didn't realise `git-cliff` was going to do this job for crypto stuff.

> Of course all of this might become even easier once we start doing releases, hopefully next week.

:rocket:

**Comment by poljar** [comment]
> Ah, so I should not have expected it to appear in CHANGELOG.md yet?

That's correct, the changelog will be updated during the release, it'll be a bit of a mess the first time we do this since we have a mix of cliff entries and hand written entries but eventually things will stabilize.

**Pull request merged**
