### PR TITLE
Unifiy UniFFI version workspace-wide, use same for xtask job

### PR DESCRIPTION
**Pull request by gnunicorn**
- [x] switches from using `uniffi-bindgen` system binary to using it as a library and calling that from within xtask
- [x] update uniffi to latest release (`0.21.0`) from yesterday
- [x] switch MSRV to 0.21.0 to allow us to use workspace-wide-definition of dependency
- [x] switch to workspace-wide-dependency usage of uniffi

### CODE REVIEW

**Comment by jplatte** [comment]
I would prefer keeping UniFFI as a git dependency, because I'm still actively working on it. I have a branch locally that makes use of my latest changes, and while those might also be in the release, this is a temporary thing and we'd almost certainly be switching back to git soon anyways.

**Comment by gnunicorn** [comment]
> I would prefer keeping UniFFI as a git dependency, because I'm still actively working on it. I have a branch locally that makes use of my latest changes, and while those might also be in the release, this is a temporary thing and we'd almost certainly be switching back to git soon anyways.

Does it really make a difference? If _this_ commit has the release rather than the git? The point of this PR is to uniffy (ha!) that in once `Cargo.toml` so that in future use, switching branches always switches both the dep and the runner...

You can and should switch to using any git version whenever that is needed.

**Review by jplatte — APPROVED** [review]
Two more things, otherwise looks good:

1. Can you please remove the word "pin" from the commit message? We're not pinning to an exact version, we are just switching to the crates.io release (pinning would be using an exact version constraint like `uniffi = "=0.21.0"`).
2. See inline comment.

**Comment by gnunicorn** [comment]
> Can you please remove the word "pin" from the commit message?

There's no commit with the word "pin" in it (or any variation thereof). you mean the github PR? Sure.

**Pull request merged**
