### PR TITLE
Use server-supported matrix versions to decide paths of later requests

### PR DESCRIPTION
**Pull request by jplatte**

### CODE REVIEW

**Review by gnunicorn — APPROVED** [review]
lgtm

**Comment by poljar** [comment]
What's the state of this? Why is CI borked? Is this the PR that deadlocked?

**Comment by jplatte** [comment]
Yeah, this deadlocked things. I'll check whether this still applies with the test code changes from the builder PR once that one is merged.

**Comment by poljar** [comment]
Oh, this doesn't introduce any new locks, so I don't think it's a deadlock. 

The constructor sends out a new request out which isn't mocked by our tests. Request retrying kicks in and our tests get stuck in a retry loop for way too long.

**Pull request merged**
