### PR TITLE
Retry decryptions based on the room key stream of the OlmMachine

### PR DESCRIPTION
**Pull request by poljar**
This is a partial fix for https://github.com/matrix-org/matrix-rust-sdk/issues/4189.

The fix works if you don't use the cross-process lock, otherwise the stream gets destroyed and updates don't come in anymore.

Opening as a draft, still needs a test.

### CODE REVIEW

**Comment by richvdh** [comment]
So this fixes EXA but not EXI?

**Comment by poljar** [comment]
Gah, trying to write a test for this and I just realized that I need to delay the delivery of the room key so I can have the following conditions:

1. Have the timeline open
2. Let the main client/timeline receive the message, an UTD
3. Have the notification client receive the room key just now
4. Watch the UTD resolve itself because the notification client tells the timeline that the room key has been received

I guess I'll have to write the test in complement-crypto.

**Comment by bnjbvr** [comment]
> delay the delivery of the room key

Our testing suite has something like this: https://github.com/matrix-org/matrix-rust-sdk/blob/a6e1f05957524b0fc28d4d6db89ff06b9bccd334/testing/matrix-sdk-integration-testing/src/tests/sliding_sync/room.rs#L682-L729

ToDevice events are evicted from a server response on purpose, and under the control of the testing code.

**Comment by poljar** [comment]
> ToDevice events are evicted from a server response on purpose, and under the control of the testing code.

Well yes, wiremock can also [delay responses](https://docs.rs/wiremock/latest/wiremock/struct.ResponseTemplate.html#method.set_delay), but then I'd have to mock a lot of things to get the E2EE and notification client working.

**Comment by poljar** [comment]
Alright, backpaginating the event into the timeline worked as well.

**Pull request merged**
