### PR TITLE
use RoomId and UserId over string, use setter method names in Room

### LINKED ISSUE #7: Some setter methods are named as getters.
There are a couple of methods in the [room.rs](https://github.com/matrix-org/matrix-rust-sdk/blob/master/src/models/room.rs#L166) file that are setters but are named as getters.

We should stick to the naming convention described in the [Rust style guide](https://doc.rust-lang.org/1.0.0/style/style/naming/README.html#getter/setter-methods-[rfc-344])

### LINKED ISSUE #8: Switch to using Ruma RoomId and UserId types.
We are using strings for room ids and user ids in many places, this creates friction when making requests since they all expect the higher level ruma-identifier types.

This has been done because we otherwise have friction when we need to compare the room id or user id to a string (e.g. a state key to a user id).

Since https://github.com/ruma/ruma-identifiers/issues/14 will be worked one, we can switch to the higher level types and have easy comparison with strings.

### PR DESCRIPTION
**Pull request by DevinR528**
Resolves #7 
Resolves #8 

Signed-off-by: Devin Ragotzy devin.ragotzy@gmail.com

I hope it's ok for me to work on this as much as I am, I am enjoying working with you?

### CODE REVIEW

**Comment by poljar** [comment]
Of course it's ok, help is very much appreciated. :D

**Comment by DevinR528** [comment]
I forgot about the `encryption` feature, I can try getting all of it to use `RoomId` and `UserId` or I can stay away since that's your area?

**Comment by poljar** [comment]
Feel free to pick it up. I'll resolve any merge conflicts if the change interferes.

**Comment by DevinR528** [comment]
I left the `SqliteStore` user_id as a `Arc<String>` otherwise the compiler complains about `UserId not impling sqlx::type::Type and sqlx::core::encode::Encode`, I think other than that this is ready for you to review.

**Pull request merged**
