### PR TITLE
Commit yarn.lock files

### PR DESCRIPTION
**Pull request by georgyo**
This is related to https://github.com/NixOS/nixpkgs/pull/186316, the lack of any kind of lock file in this packages prevents tools like nix from deterministically downloading dependencies and causes the build to fail.

I also converted two instances of `npm` to `yarn` since most if not all matrix js packages are using yarn.

### CODE REVIEW

**Review by gnunicorn — COMMENTED** [review]
this looks fine for me, but I am not sure if we have to expect fallout if we do this... @Hywan ?

**Comment by Hywan** [comment]
I'm not familiar with the JavaScript ecosystem. Why using `yarn` over `npm`? Other than that, I'm fine with commiting the lock file.

**Comment by jplatte** [comment]
In my experience, `yarn` is a whole lot faster than `npm`. Overall since the introduction of npm lockfiles (many years ago), they are pretty similar in terms of functionality AFAIK.

**Comment by Hywan** [comment]
If we switch to `yarn`, we need to:

1. Update documentation,
2. Update the CI scripts.

But, we are also using `wasm-pack`, which runs `npm` behind the scene. I'm not comfortable using two different tools and assuming if they are absolutely compatible.

**Comment by Hywan** [comment]
Hello @georgyo,

I acknowledge your issue with nixpkgs. We don't want to use `yarn` for technical reasons, but we are OK to use a lock file with NPM. Are you OK to update your PR to add a `package.lock` instead? If you don't want, I'm fine doing it too.

Thanks!

**Comment by georgyo** [comment]
I don't think this is actually required for my use case. I'll create a new PR using NPM if it become needed.

**Pull request closed without merging**
