### PR TITLE
refactor: Use event handlers in emoji_verification example

### PR DESCRIPTION
**Pull request by jplatte**
Haven't tested this, would appreciate instructions for how best to do that 😅

### CODE REVIEW

**Comment by jplatte** [comment]
Own (to-device) verification worked right away, for verifying another account (after the bot was launched) I had to get rid of the logic to only react to these events on the very first sync of the bot. Do you know what that was for?

**Comment by poljar** [comment]
> Own (to-device) verification worked right away, for verifying another account (after the bot was launched) I had to get rid of the logic to only react to these events on the very first sync of the bot. Do you know what that was for?

If you run the example multiple times it will receive some older events as well, I think this is a hack so it only reacts to live events.

**Comment by poljar** [comment]
But you shouldn't be required to initiate the verification before starting the bot, in fact you can't initiate the verification since the E2EE device doesn't exist before you start the bot.

Let me test to see what's going on.

**Comment by poljar** [comment]
Oh, the fixup seems to have missed its target as well.

**Comment by jplatte** [comment]
How so? I managed to verify a device after the fixup..

**Review by poljar — APPROVED** [review]
Right, this works. Just make sure the fixup applies to the right commit.

**Comment by jplatte** [comment]
Oh, yeah I failed at the `--fixup` command (used `HEAD~` instead of `HEAD`). I'll just let GitHub squash, it's hardly going to amend an existing commit on `main` 😄

**Pull request merged**
