### PR TITLE
Add tombstone event handling/emitting, fix panic in calculate name

### PR DESCRIPTION
**Pull request by DevinR528**
I hope this is focused enough, if not I can separate them into 2 PRs.

### CODE REVIEW

**Comment by DevinR528** [comment]
Good idea. Do you have any idea why the `heroes` Vec is always empty?

**Comment by poljar** [comment]
If there are no heroes passed by the server ruma creates an empty vector for us.

**Comment by DevinR528** [comment]
I found this testing my client and I never got a populated room summary, I guess I was more wondering if the matrix server is actually dealing with this, or am I doing something wrong? We do handle it in `AsyncClient::sync` with `Room::set_room_summary`.

**Comment by poljar** [comment]
Either the server isn't sending it or there's a parsing error in ruma. You could check with mitmproxy what the server is sending you.

**Comment by DevinR528** [comment]
Thanks that looks like a really helpful tool!

**Pull request merged**
