### PR TITLE
feat(sdk) Revamp Sliding Sync List state lifetime

### PR DESCRIPTION
**Pull request by Hywan**
Partly address https://github.com/matrix-org/matrix-rust-sdk/issues/1696.

This PR must be reviewed commit-by-commit, otherwise it's going to be a nightmare.

Here is a summary of what it does:

* It exports `RoomListEntry` into its own module,
* It renames some enum variants without keeping the backward compatibility (and that's fine, as discussed with the mobile teams),
* It removes unused fields in `SlidingSyncList` (the `full_sync_*` fields), but methods on the builder are still here,
* The `send_updates_for_items` parameter in the list builder, or the field in `SlidingSyncList` is removed, as it's always set to `true`, nobody wants to set it to `false`,
* The `SlidingSyncList::*range*` methods have been revamped a little bit, they are more consistent,
* Changing the ranges of a list will automatically reset it, so the next iteration in the `SlidingSync::stream`'s loop will take the new configuration into account. No need to restart the stream for that! A next PR will entirely remove the need to restart a stream by cancelling the current iteration of the stream's loop, so that a new request with the new configuration will be sent immediately,
* Extract the giant module doc' of `SlidingSync` into a `README.md` file,
* Lists are no longer removed from `SlidingSync`. It was an internal thing, but it was super annoying. The code is simpler and more efficient.
* Remove tons of panics in the code (`unwrap`, out of bounds accesses [tons of them] etc.),
* Fewer locks (since `find_rooms_in_list` has been entirely removed), and fewer allocations, thus reducing memory usages,
* Many many bug fixes in how `SyncOp` are handled: out-of-access, detecting bad responses, ops were badly handled etc.
* `SlidingSync::stream` no longer resets lists, one has to call `SlidingSync::reset_lists` to achieve that. But it's not supposed to be used if you want to keep the same behaviour.

Edit:

* This patch has found a bug on the Sliding Sync Proxy (aka the server), and has implemented a workaround for it, https://github.com/matrix-org/sliding-sync/issues/52.

And obviously, tons of new tests 😋.

### CODE REVIEW

**Comment by Hywan** [comment]
Please hold on the review a little bit. I may have misunderstood the meanings of some `SyncOp`. Plus, I've no updated `matrix-sdk-ffi` yet.

**Comment by poljar** [comment]
There's a typo in 492e08598c5b6921d6d4c06b2a777093f3042c83:

> `Selective` does allow a
user to modufy the ranges, but there is no real ranges with `Growing` or
`Paging`. Let's make it an explicit error.

Modufy instead of modify.

**Review by poljar — CHANGES_REQUESTED** [review]
Left a couple of nits. I think we might want to consider using the `Range` type more. Perhaps even at the Ruma level to directly serialize/deserialize into the `Range` type.

**Comment by Hywan** [comment]
Here is the PR, https://github.com/matrix-org/matrix-rust-sdk/issues/1739

**Pull request merged**
