### PR TITLE
fix: reify reformat of `missing_session_devices_by_user`

### PR DESCRIPTION
**Pull request by bnjbvr**
`itertools::format` is known to cause issues when its display implementation is being used multiple times, as it consumes the iterator it was given (and that can only happen once, unless caching it). This is bad, as our production apps may have multiple subscribers they will run into a panic.

The fix is to reify the debug string before it's logged, so the tracing consumer will only see a string, and not the display implementation that would panic on the second use.

### CODE REVIEW

**Review by jplatte — APPROVED** [review]
Alright, I'm still pretty confused but I suppose you must have tested this. ~~Just to be sure, can you test whether moving the missing sessions into a let binding without stringifying works as well (if you haven't)?~~

**Comment by bnjbvr** [comment]
Ah, good catch, I've removed the referenced issue, since it's a rageshake: https://github.com/vector-im/element-x-ios-rageshakes/issues/1149

The EX apps would use multiple tracing subscriber, but iterators that have been `format`ted can be consumed only once. The `itertools::format` helper returns a struct that stores the iterator, and once it's displayed, the iter is consumed by ownership, so subsequent calls will panic — even when the iterator can be cloned or copied.

**Comment by jplatte** [comment]
Ohhhh so with multiple subscribers, one `info!` call with a `?foo` parameter actually debug-prints `foo` multiple times. That makes sense then, and my other workaround doesn't. Thanks for the details!

**Comment by bnjbvr** [comment]
> Just to be sure, can you test whether moving the missing sessions into a let binding without stringifying works as well (if you haven't)?

I've tried just that, but since the debug implementation is still called multiple times, the panic still happens.

**Pull request merged**
