### PR TITLE
matrix-sdk-test: Remove duplicate test_data folder, leave top-level

### PR DESCRIPTION
**Pull request by DevinR528**

### CODE REVIEW

**Comment by DevinR528** [comment]
The test that just failed for me is the other flaky test. I've seen this one fail more often @MTRNord

**Comment by DevinR528** [comment]
I ran the command in `matrix-rust-sdk/matrix-sdk`, are you using `cargo publish-all` or are you also running it inside the respective folders?

I had to remove this
```bash
error[E0432]: unresolved import `matrix_sdk_base::CustomOrRawEvent`
  --> src/lib.rs:42:27
   |
42 | pub use matrix_sdk_base::{CustomOrRawEvent, EventEmitter, Room, Session, SyncRoom};
   |                           ^^^^^^^^^^^^^^^^ no `CustomOrRawEvent` in the root

error: aborting due to previous error

For more information about this error, try `rustc --explain E0432`.
error: could not compile `matrix-sdk`.
```
but once I did I can't seem to get it to fail
```bash
   Compiling matrix-sdk-common v0.1.0
   Compiling matrix-sdk-crypto v0.1.0
   Compiling matrix-sdk-base v0.1.0
   Compiling matrix-sdk v0.1.0 (/home/devinr/aprog/rust/__forks__/matrix-rust-sdk/target/package/matrix-sdk-0.1.0)
    Finished dev [unoptimized + debuginfo] target(s) in 41.61s
   Uploading matrix-sdk v0.1.0 (/home/devinr/aprog/rust/__forks__/matrix-rust-sdk/matrix_sdk)
```

**Comment by poljar** [comment]
Since `cargo publish-all` is marked as experimental and with warnings I'm publishing stuff the old fashioned way, yes.

**Comment by DevinR528** [comment]
If this looks ok I still have to convert `matrix_sdk` and `matrix_sdk_crypto` to use this.

**Pull request merged**
