### PR TITLE
Exhaustive sync_events::Response conversion

### PR DESCRIPTION
**Pull request by jplatte**
Unfortunately I had to duplicate the entire destructuring statement for `sync_events::Response` since attributes on field patterns or `..` rest-field patterns are not supported. (cc https://github.com/rust-lang/rust/issues/81282#issuecomment-822376089)

From here it should be easy to add `EncryptionInfo` as discussed without further changes to Ruma, right? If so, this closes ruma/ruma#35.

### CODE REVIEW

**Comment by jplatte** [comment]
This whole thing would look less ugly once it's more directly supported with a lint that triggers on reachable rest patterns. I've opened https://github.com/rust-lang/rust/issues/84332 for that.

**Comment by jplatte** [comment]
This probably obsoletes #136 too, right?

**Comment by poljar** [comment]
> This probably obsoletes #136 too.

Well yes and no, yes in its current form. We still need a PR to include the encryption info and what not.

**Comment by jplatte** [comment]
Yes, of course :)

Should I open an issue about that, as a replacement for ruma/ruma#35 and #136?

**Comment by poljar** [comment]
I mean sure if you want to, though I can also just keep that in my head since I'll work on #136 this week.

**Comment by jplatte** [comment]
Okay, then I won't create an issue. I'm done force-pushing by the way 😅

**Comment by poljar** [comment]
Thanks, merged.

**Pull request merged**
