### PR TITLE
Consistently use Ruma's Owned*Id types

### PR DESCRIPTION
**Pull request by jplatte**
… instead of `Arc<*Id>`.

### CODE REVIEW

**Comment by poljar** [comment]
I think this is missing an explanation on why we're doing this.

**Comment by jplatte** [comment]
Right, that's really just simplicity. Do you want me to update the commit message?

Side note: Ruma's owned types are configurable as to how they're internally represented (`Box` / `Arc`) via `rustflags`, though for the `Arc` version to make sense it would be good if we had more accessors that return owned IDs rather than references which `.to_owned()` would then newly allocate for even with the `Arc` solution.

**Comment by poljar** [comment]
> Right, that's really just simplicity. Do you want me to update the commit message?

Perhaps a comment would help here, yes. Though some of these have the potential to increase memory usage, i.e. the one in `ReadOnlyDevice` (nevermind the crappy naming). As you suggested in chat, some of these might need to get the `struct Foo { inner: Arc<FooInner> }` treatment to avoid this risk.

> Side note: Ruma's owned types are configurable as to how they're internally represented (`Box` / `Arc`) via `rustflags`, though for the `Arc` version to make sense it would be good if we had more accessors that return owned IDs rather than references which `.to_owned()` would then newly allocate for even with the `Arc` solution.

I'm aware of this, though not sure if it makes sense for us to switch to `Arc`.

**Comment by jplatte** [comment]
I updated the commit description. Regarding the `Arc<Inner>` pattern, I have a separate branch that depends on this one that implements that change for `Store` and `OlmMachine`. Should we do both in one PR?

**Comment by poljar** [comment]
> I updated the commit description. Regarding the `Arc<Inner>` pattern, I have a separate branch that depends on this one that implements that change for `Store` and `OlmMachine`. Do you prefer having both in one PR?

Ah you already have both things in flight, no need to bring them here.

**Review by poljar — APPROVED** [review]

**Comment by Hywan** [comment]
Thanks! That's a nice improvement.

**Pull request merged**
