### PR TITLE
Export "unstable-synapse-quirks" feature from ruma

### PR DESCRIPTION
**Pull request by aledomu**

### CODE REVIEW

**Comment by poljar** [comment]
Out of interest could you share what you're using this feature for?

As I already mentioned I'm fine with exposing this.

**Comment by aledomu** [comment]
There are API endpoints that don't work well with Synapse even though it follows the spec. That's where I need `ruma` to adapt to its behaviour, given that it's the most common server among instances.

**Comment by poljar** [comment]
> There are API endpoints that don't work well with Synapse even though it follows the spec. That's where I need `ruma` to adapt to its behaviour, given that it's the most common server among instances.

Yes I know why the flag exists, I was more wondering which endpoints you have trouble with.

**Comment by aledomu** [comment]
At the moment, this one: https://matrix.org/docs/spec/client_server/r0.6.0#get-matrix-client-r0-thirdparty-protocols

**Pull request merged**
