### PR TITLE
fix(bindings): use the same library name for all platforms in the xcframework

### PR DESCRIPTION
**Pull request by Johennes**
Fixes: #3528

- [ ] Public API changes documented in changelogs (optional)

### CODE REVIEW

**Review by poljar — COMMENTED** [review]
This looks fine, but hard to double check without a Apple machine.

@stefanceriu can you double check if this is fine for you guys?

**Comment by stefanceriu** [comment]
Yup yup, leave it with me, it might just take me a bit to get to it 👍

**Review by stefanceriu — APPROVED** [review]
Alrighty, I had a go at building the whole thing and it not only looks great but it also works 😁 

🚀 it and thank you for handling it yourself!

**Comment by Johennes** [comment]
Thanks for reviewing it so quickly! 🙂

**Comment by stefanceriu** [comment]
@Johennes made a new release here https://github.com/matrix-org/matrix-rust-components-swift/releases/tag/v1.1.68 if you want to try it out. Seems fine on our side fwiw.

**Comment by Johennes** [comment]
Tested and works in RN as well. 🎉 

Thanks again!

**Pull request merged**
