### PR TITLE
clippy: Enforce the `redundant_clone` lint rule

### LINKED ISSUE #3683: code base: enforce the `redundant_clone` Clippy lint
This would catch a few useless `clone()` calls in the code base.

To work on this:

- add `-Wclippy::redundant_clone` to [this list](https://github.com/matrix-org/matrix-rust-sdk/blob/9e9df163b903e2a5ec415b1a708a85cf64e48d4b/.cargo/config.toml#L41).
- compile with Clippy, using `cargo xtask ci clippy` and fix all the issues it finds.

### PR DESCRIPTION
**Pull request by almet**
Fixes #3683

### CODE REVIEW

**Comment by almet** [comment]
I don't understand why clippy is failing on the CI, especially as the lines it mention doesn't exist locally for me, and I don't see the same errors when running the command.

Any idea why that is?

**Comment by bnjbvr** [comment]
It looks like the first attempt at this CI task checked out the wrong commit, which is surprising; I retried and now we're running into caching issues. Investigating with other repo maintainers, I wonder if we could empty the caches or cause a new run on a new commit (folding the fixup commit into the other one and force-pushing might do the trick!).

**Comment by almet** [comment]
> (folding the fixup commit into the other one and force-pushing might do the trick!).

Just did, let's see :-)

**Comment by bnjbvr** [comment]
Hmm, it didn't work. Can you try rebasing over main, please? (this might introduce new redundant clones, if new PRs introduced some)

**Comment by bnjbvr** [comment]
Ah, turns out I can now repro the local Clippy failures when running with `cargo xtask ci clippy`, so you should be able to as well.

**Comment by almet** [comment]
Thanks for your support. We should be good to go.

**Review by bnjbvr — APPROVED** [review]
Thanks very much :partying_face: And congrats on your first PR!

**Pull request merged**
