### PR TITLE
Add rough example in the FFI bindings README

### PR DESCRIPTION
**Pull request by NiallBunting**
This gives a rough overview how to use the FFI. It's not a fully working copy and paste example but a good start.

Signed-off-by: Niall Bunting <git@niallbunting.com>

### CODE REVIEW

**Review by Hywan — CHANGES_REQUESTED** [review]
Hello, and thanks for your contributions!

I'm not sure it's an optimal way to explain it.

Firstly, your code is written in Kotlin if I don't misunderstand. I believe an initial good explanations would be: how to compile the bindings, how to generate the bindings for Kotlin, how to use it in a project etc., before showing any code.

What do you think?

**Comment by NiallBunting** [comment]
I'm not writing that in kotlin but dart.

I just wanted to put a really high level reference example to help people get started. I do think further info is required.

**Review by bnjbvr — CHANGES_REQUESTED** [review]
Thanks for the changes. We're not using or officially supporting the Dart bindings, so I don't think we should accept those as reference examples in the README, or it would send the wrong message (that we're supporting Dart). Would you be interested in writing a small Kotlin or Swift example instead?

**Comment by poljar** [comment]
I agree with @bnjbvr here. It would be another story if/when `uniffi` officially supported Dart, but as it is you require 3rd party support to get Dart working.

As this has not seen activity for a while I'm going to close this one, please feel free to open a new PR if you'd like to provide an example in another language.

**Pull request closed without merging**
