### PR TITLE
Bump ruma

### PR DESCRIPTION
**Pull request by julioromano**
Needing this commit in the Matrix Rust SDK in order to complete the location sharing feature: https://github.com/ruma/ruma/commit/d0f11f007551b761afe93b53164cb0fd6d4d8fb3

### CODE REVIEW

**Comment by julioromano** [comment]
As spoken with @jplatte in chat, this is not release critical. We just need this commit to eventually land in the SDK soon-ish (~1week). Thanks

**Review by Hywan — COMMENTED** [review]
Can re-update to the latest Ruma commit please?

**Comment by jplatte** [comment]
@Hywan There's no point. We will only do this after the Ruma changes we're depending on are properly merged, which won't be this week.

**Comment by julioromano** [comment]
Superseded by https://github.com/matrix-org/matrix-rust-sdk/pull/2187

**Pull request closed without merging**
