### PR TITLE
feat(sdk): Remove hacks for Sliding Sync ranges

### PR DESCRIPTION
**Pull request by Hywan**
Now that https://github.com/matrix-org/sliding-sync/issues/52 is fixed, we can remove the hacks introduced in https://github.com/matrix-org/matrix-rust-sdk/pull/1699 to handle bad ranges.

It may fix some bugs we have now. The hacks were intended to work with a buggy proxy, not with a valid one (the behaviors were very different).

Let's try this.

### CODE REVIEW

**Review by stefanceriu — APPROVED** [review]
lgtm 👍

**Review by jplatte — COMMENTED** [review]
We shouldn't merge this to `main` with an unversioned reference to the proxy container, right? Otherwise LGTM.

**Comment by Hywan** [comment]
@kegsay told me to use `main`. Can you confirm if it's fine? Was there a new release we can use maybe?

**Comment by Hywan** [comment]
https://github.com/matrix-org/sliding-sync/releases/tag/v0.99.2 was just released an hour ago. Let's use this one.

**Pull request merged**
